<?php
/**
 * Configuration file for the CMS.
 */

// Password for the admin panel.
// This is a hash generated by password_hash().
// The original password is 'danilo'.
define('ADMIN_PASSWORD_HASH', '$2y$10$zQPtx7Wj2prNnKnl6IMNB.Rh9Bo9A2/kuMCZUsDZKqEVkJCfLKwDe');
?>
