<p>Questa mattina Marco, mio marito, &egrave; uscito prima del solito. Cascasse il mondo deve andare a correre per tenersi in forma, anche qui in vacanza, anche se potrebbe restarsene a letto con me e fare ben altra attivit&agrave; fisica. A dire il vero negli ultimi due anni i nostri rapporti sessuali sono diminuiti sempre di pi&ugrave;.</p>
<h2><strong>Chiama subito: <a href="tel:899.89.82.88" data-track-content="" data-content-name="899898288" data-content-piece="www.raccontierotici24.it">899.89.82.88</a></strong></h2>
<p><img src="//www.raccontierotici24.it/storage/chicon.png" alt="svizzera" width="26" height="17" /> Per accedere alle chiamate erotiche dalla Svizzera componi i seguenti numeri:</p>
<ul>
<li>CHIAMATE EROTICHE ETERO: <a style="font-size: 15px;" href="tel:0906.906.901" data-track-content="" data-content-name="0906906901" data-content-piece="www.raccontierotici24.it"> 0906.906.901</a> A 0,99 CHF AL MINUTO</li>
<li>CHIAMATE EROTICHE MATURE: <a style="font-size: 15px;" href="tel:0906.906.666" data-track-content="" data-content-name="0906906666" data-content-piece="www.raccontierotici24.it">0906.906.666</a> A 0,99 CHF AL MINUTO</li>
<li>CHIAMATE EROTICHE TRANS: <a style="font-size: 15px;" href="tel:0906.869.869" data-track-content="" data-content-name="0906869869" data-content-piece="www.raccontierotici24.it"> 0906.869.869</a> A 0,99 CHF AL MINUTO</li>
</ul>
<p>L'abitudine, la stanchezza per il lavoro e magari qualche interesse extraconiugale ci hanno distratti dalle nostre evoluzioni a letto che sono sempre state notevoli. Anche questa storia della corsa non mi convince, mi fa pensare che in realt&agrave; si prepari per un'altra o che magari di solito vada a correre con un'amica.</p>
<p>Lui ha un bel fisico e quando &egrave; sudato e sotto sforzo diventa irresistibile, io amo il corpo degli uomini quando sono affaticati, per questo mi sono iscritta in palestra. N&eacute; io n&eacute; mio marito siamo mai stati veramente gelosi, ci siamo lasciati reciproca libert&agrave; senza bisogno di prendere accordi, semplicemente non chiediamo dove l'altro vada e se proprio lo si fa si finge poi di credere a qualsiasi scusa ci si dica, anche la peggiore. Cos&igrave; abbiamo vissuto diverse avventure lungo questi anni.</p>
<p>Vuoi spendere di meno?</p>
<p>Componi il numero&nbsp;&nbsp;<strong><a href="tel:0689083867" data-track-content="" data-content-name="0689083867" data-content-piece="www.raccontierotici24.it">06.890.83.867</a>&nbsp;</strong>e ascolta il messaggio gratuito, risparmi fino a 50 centesimi di euro al minuto.</p>
<p><a href="tel:0689083867"><img class="alignnone size-full wp-image-101" style="display: block; margin-left: auto; margin-right: auto;" src="//www.raccontierotici24.it/wp-content/uploads/2015/08/mature-al-telefono-con-carta-di-credito.jpg" alt="mature al telefono con carta di credito" width="687" height="271" /></a></p>
<p>Io, dopo un primo periodo assolutamente platonico, ho lasciato le redini per farmi trasportare dove capitava. Ho anche dovuto cambiare palestra per questa scelta di vita, infatti la proprietaria della struttura non ha gradito vedere il suo ragazzo che mi scopava negli spogliatoi. A questo punto non mi resta che andare in spiaggia e sperare di incontrare Gianni, il simpatico nonch&eacute; superdotato vicino di ombrellone da cui sono riuscita ad ottenere solo 5 minuti di piacere. Anche in questo caso &egrave; sua moglie a non gradire la mia vicinanza. Nemmeno lei avrebbe diritto di parola in quanto l'ho vista mentre flirtava con mezza spiaggia, per&ograve; nel gioco dei ruoli coniugali va bene anche tenere certe posizioni.</p>
<p>Quell'immagine composta dai suoi muscoli e dal costume scelto in modo che si vedessero il pi&ugrave; possibile le sue misure gli d&agrave; un tono un po' da coatto e un po' da uomo alpha. In effetti io gli ho fatto appena capire che forse ero interessato a lui, eppure dopo due ore mi sono ritrovata nella cabina col suo splendido arnese tra le gambe. &Egrave; difficile trovare uomini che vogliano e sappiano prendere al volo queste occasioni e di certo non voglio perdere la possibilit&agrave; di avere altri assaggi della sua irruenza.</p>
<p>Il bikini bianco che ho comprato non lascia nulla all'immaginazione, soprattutto una volta uscita dall'acqua. La depilazione completa finisce l'opera, lasciandomi praticamente nuda sulla sdraio. Questa volta c'&egrave; solo lui, si avvicina mentre mi asciugo sulla sdraio e subito mi dice che la moglie &egrave; andata a visitare un museo in citt&agrave; con altri vacanzieri. Alzo gli occhiali da sole, lo guardo per un secondo e mi sento dire che &egrave; l'occasione giusta per approfondire il discorso di ieri.</p>
<p>Potrei fare un po' di resistenza, fingere di non essere quel tipo di donna, spiegare che ieri &egrave; stato solo un incidente di percorso e invece mi ritrovo gi&agrave; a camminare verso l'albergo, con la borsa in mano e con lui che mi prende sotto braccio. Nemmeno adesso che ha appoggiato una mano sul culo ho voglia di fermarlo, sono gi&agrave; proiettata alla scopata. Siamo in corridoio e gi&agrave; sta provando a scoparmi, cos&igrave; &egrave; troppo. Lo porto in camera mia che &egrave; l&igrave; a dieci metri e appena dentro restiamo bloccati e in silenzio assoluto.</p>
<p>La sua erezione resta immutata, perfetta, cos&igrave; come io continuo ad essere bagnatissima. Eppure stiamo guardando mio marito che monta la moglie del mio amante che sar&agrave; anche interessata alla cultura museale ma in questo caso mi sembra presa pi&ugrave; dalla scoperta dell'anatomia. Neanche hanno notato la nostra presenza, lei alla pecorina che gli chiede di continuare e lui che continua a scoparla come un ossesso, come non fa pi&ugrave; da anni con me. Bisogna fare qualcosa, restare cos&igrave; &egrave; pericoloso anche perch&eacute; la porta &egrave; aperta.</p>
<p>Cos&igrave; mi inginocchio davanti al mio amante cornuto e inizio a fargli un pompino. Adesso posso chiudere la porta e s&igrave;, adesso ci notano e quello che vedono li lascia nello stesso identico stato marmoreo che ci aveva colpiti pochi secondi fa. Lei prova a dire qualcosa ma non le escono le parole dalla bocca, mio marito invece mi guarda eccitatissimo e riprende a scopare la donna di cultura.</p>
<p>Ci avviciniamo al letto, mi spoglio completamente e mi sdraio mettendo la faccia proprio sotto alla nuova amante di mio marito. Non faccio in tempo a farmi un'idea precisa del suo viso che gi&agrave; mi sento scopata con forza e non ho voglia di pensare ad altro che a quell'enorme uccello che mi sta aprendo. Sento arrivare mio marito e vedo lei coricarsi esausta sul letto mentre guarda il suo uomo impegnato tra le mie gambe. Il mio istinto competitivo non pu&ograve; lasciare che io sia trattata allo stesso modo di lei, voglio di pi&ugrave;. Allora sfil&ograve; l'uccello e lo punto sul mio culo.</p>
<p>Non ho bisogno di dire qualcosa, lui inizia ad affondarci dentro. Guardo lei, &egrave; di nuovo a bocca aperta, evidentemente non crede ai suoi occhi, cos&igrave; ho vinto di nuovo. Almeno cos&igrave; &egrave; fino a quando mio marito non decide di trattarla allo stesso modo mettendola in ginocchio e iniziando a penetrarla da dietro. A questo punto tocca a lei guardarmi con soddisfazione. Dovrei arrabbiarmi, dovrei alzare la posta e invece mi scappa un sorriso di complicit&agrave; che apre la strada ad un'amicizia di coppia che lascer&agrave; il segno nelle nostre vite.</p>