<p>La ricerca di emozioni sempre pi&ugrave; forti mi tiene compagnia fin da quando ho avuto le prime esperienze sessuali. Sono passato dalla scelta delle ragazze a seconda del tipo di fisico, fino alle prime timide esperienze omosessuali con quegli amici troppo pieni di ormoni per resistere all'offerta di un po' di sesso orale, anche se proveniva da un uomo.</p>
<h2 style="text-align: center;"><strong>Chiama subito: <a href="tel:899.89.82.45" data-track-content="" data-content-name="899898245" data-content-piece="www.raccontierotici24.it">899.89.82.45</a></strong></h2>
<p><img src="/storage/chicon.png" alt="svizzera" width="26" height="17" /> Per accedere alle chiamate erotiche dalla Svizzera componi il seguente numero:</p>
<ul>
<li>CHIAMATE EROTICHE TRANS: <a style="font-size: 15px;" href="tel:0906.869.869" data-track-content="" data-content-name="0906869869" data-content-piece="www.raccontierotici24.it"> 0906.869.869</a> A 0,99 CHF AL MINUTO</li>
</ul>
<p>Questo andazzo &egrave; continuato fino a quando mi sono sposato, poi per qualche anno mi sono calmato. La nuova esperienza mi aveva distratto dagli istinti che per&ograve; ben presto si sono rifatti sentire con tutta la loro forza. Ho cominciato a cercare qualche uomo tramite le chat, non avevo voglia di rivolgermi ai siti per incontri sessuali. Poi per&ograve;, non trovando nulla che mi attirasse ho deciso di cedere e iscrivermi.</p>
<p>Una volta entrato mi hanno chiesto di inserire i gusti sessuali. Ho selezionato tutte le opzioni, sperando di trovare una donna o un uomo che mi ispirasse. Ho trascorso pi&ugrave; di un'ora alla ricerca di foto o informazioni che mi solleticassero quando mi arriva un messaggio nella posta privata. Vado a controllare e sono subito colpito da questa donna meravigliosa.</p>
<p>Vuoi spendere di meno?</p>
<p>Componi il numero <strong><a href="tel:0689083867" data-track-content="" data-content-name="0689083867" data-content-piece="www.raccontierotici24.it">06.890.83.867</a>&nbsp;</strong>e ascolta il messaggio gratuito, risparmi fino a 50 centesimi di euro al minuto.</p>
<p><a href="tel:0689083867"><img class="alignnone size-full wp-image-101" style="display: block; margin-left: auto; margin-right: auto;" src="//www.raccontierotici24.it/wp-content/uploads/2015/08/mature-al-telefono-con-carta-di-credito.jpg" alt="mature al telefono con carta di credito" width="687" height="271" /></a></p>
<p>Seno piccolo come piace a me, gambe lunghe e un intimo di pizzo nero da togliere il fiato. L'ammirazione ha lasciato immediatamente il posto alla sorpresa: il profilo non lascia dubbi, il contatto &egrave; un trans. Quella del trans &egrave; una fantasia che non mi &egrave; mai passata per la testa. Non so per quale motivo ma tra le mille fantasie perverse che hanno riempito la mia testa e il mio organo genitale, un transessuale non &egrave; mai capitato.</p>
<p>La notizia che si trattasse di un trans, dopo la sorpresa, mi ha causato un'eccitazione senza precedenti. Ho deciso di rispondere, di saperne di pi&ugrave;. Da l&igrave; &egrave; nato il dialogo con una persona meravigliosa e con una carica erotica che mai avevo riscontrato in altri soggetti. Abbiamo impiegato pochissimo a fissare un appuntamento in un bar vicino casa sua. Pur sapendo che incontrandolo in un luogo pubblico in cui era ben conosciuto, avrei immediatamente ufficializzato la mia avventura, ho accettato senza alcun problema, anzi, con una voglia sempre crescente.</p>
<p>Si &egrave; presentato vestito da perfetta donna. Ancora pi&ugrave; bello di quanto l'avessi visto in foto. Solo la voce tradiva il suo lato mascolino, per il resto di sicuro mi sarei girato per strada a guardare un pezzo di donna tanto bella. Il caff&egrave; &egrave; durato pochissimo, era evidente la nascita di un feeling immediato. Ha chiesto se volessimo salire su da lei, le ho risposto che stavo per chiederle la stessa cosa. Le si sono illuminati gli occhi e siamo usciti dal bar senza pagare, quindi &egrave; stato un po' come gridare a tutti i clienti che s&igrave;, stavamo per andare a scopare.</p>
<p>Ancora una volta, invece di provare vergogna, la mia eccitazione &egrave; aumentata ancora di pi&ugrave;. Si &egrave; spogliata con sapiente lentezza mentre io ero gi&agrave; nudo da qualche minuto. Quando &egrave; rimasta senza vestiti ho potuto ammirare un uccello meraviglioso, perfetto. Lungo, largo e teso verso l'alto sembrava invitare la mia bocca. Cosa che ho fatto non prima di avvisare che la mia esperienza in merito al sesso orale era davvero scarsa. Aveva un sapore e un odore meravigliosi. La cappella perfettamente liscia contrastava con i rilievi del resto dell'asta. Mi ha spinto sul letto e ha ricambiato il favore. Un altro livello di bravura. Riusciva a non staccare mai le labbra facendo aderire la sua bocca al mio uccello, sembrava essersi fusa con la mia carne.</p>
<p>Ha capito che continuando cos&igrave; mi avrebbe fatto arrivare in poco tempo e allora s'&egrave; tolta e ha iniziato a leccare ogni angolo del mio corpo, regalandomi dei brividi unici. Appena tornava alla mia portata le succhiavo le stupende tette che si ritrovava, ma non si lasciava fermare cos&igrave; facilmente e fuggiva sempre via dalla mia portata. Non sapevo cosa fare, avrei voluto penetrarla ma non so come funziona in questi casi.</p>
<p>C'&egrave; qualcosa che la pu&ograve; offendere? Magari con i trans bisogna prima dimostrarsi disponibile. Lei ha letto nei miei occhi l'indecisione e s'&egrave; piegata sul letto offrendomi il culo. Ha detto di cominciare da l&igrave;. Nemmeno ricordo quali sono stati i miei primi gesti, ho solo memoria di essere dentro di lei con una foga che sembrava controllarmi. Quel culo sodo tra le mani mi faceva impazzire e lei era bollente, ero convinto di arrivarle subito dentro ma lei ancora una volta mi ferma, mi stende con la schiena sul letto, alza e allarga le mie gambe e dice che ora tocca a lei. Tocca a lei. Il cuore mi salta in gola. Non vedo l'ora.</p>
<p>Lei &egrave; di una delicatezza assoluta, almeno all'inizio. Centimetro per centimetro si fa ogni volta un po' di strada in pi&ugrave;. In poco tempo, o almeno questo &egrave; il ricordo che ne ho, mi ritrovo scopato con forza nel culo. Va gi&ugrave; decisa come se io fossi abituato ad una simile esperienza. Altro che paura di farsi male durante le prime volte. Erano anni che nessuno me lo infilava ed ero elastico come il pi&ugrave; esperto del mondo.</p>
<p>La voglia pu&ograve; pi&ugrave; dei muscoli e dei nervi. &Egrave; indemoniata e io sono al limite dell'orgasmo, non vedo l'ora che arrivi, glielo chiedo, la imploro. Lei esaudisce il mio desiderio restandomi dentro. Anche una volta finito non esce, inizia a masturbarmi con sapienza.</p>
<p>Mi porta pi&ugrave; volte sull'orlo dell'orgasmo ma poi si ferma. Poi va fino in fondo e lascia che il mio sperma coli sul mio culo e sul suo uccello che ora &egrave; un po' fuori. Il tempo per me di sospirare che riprende un lento su e gi&ugrave; che mi incastra alle sue voglie ancora oggi.</p>