<p>Sentivo solo il rumore della sua mano che violentemente mi penetrava, e i miei.. gemiti. Il silenzio era assoluto tranne questi due rumori, lui mi guardava e sorrideva. Eravamo in un "bed and breakfast" e mi stava facendo "godere come una pazza". Era il nostro primo appuntamento "da soli". C&rsquo;eravamo conosciuti in "un club prive" con i nostri rispettivi coniugi, e subito ci eravamo piaciuti.</p>
<p>Io bella donna, terza di seno, insoddisfatta del rapporto con mio marito, lui pi&ugrave; giovane, con una moglie che lo seguiva in tutto e per tutto, e con parecchie "storie" alle spalle. Quella sera avevamo fatto "sesso di coppia", con i nostri partner che cercavano di soddisfarci nel migliore dei modi, ma che non ci riuscivano. Io avevo accettato l&rsquo;esperienza del "club" per disperazione, il sesso con mio marito era ormai un "rituale" meccanico e noioso.</p>
<p>Luciano &egrave; una brava persona, ma nei nostri 22 anni di matrimonio mai &egrave; riuscito a soddisfarmi. Non ha fantasia, non ha passione, non riesce in poche parole a "farmi vibrare". Da quello che potevo capire per lui era lo stesso, ma quella sera &egrave; servita a farci conoscere e per questo &egrave; stata sicuramente una "bella sera". Nel "priv&eacute;" ci eravamo "incrociati" durante qualche gioco, e in quei momenti i nostri occhi avevano detto tutto.</p>
<p>Eravamo due "animali da letto", e adesso mentre ansimavo, mi rendevo conto che il destino con me era stato benevolo. Sandro sicuramente lo aveva capito prima, lui gi&agrave; quella sera mi aveva dato il suo numero. Mi ricordo ancora come se fosse in questo momento, mio marito e sua moglie erano in bagno, noi eravamo su due divanetti vicini ma non adiacenti, lui si alz&ograve; all&rsquo;improvviso e mi diede un fogliettino con un numero di telefono.</p>
<h2 style="text-align: center;"><strong>Chiama subito: <a href="tel:899.89.82.88" data-track-content="" data-content-name="899898288" data-content-piece="www.raccontierotici24.it">899.89.82.88</a></strong></h2>
<p><img src="/storage/chicon.png" alt="svizzera" width="26" height="17" /> Per accedere alle chiamate erotiche dalla Svizzera componi il seguente numero:</p>
<ul>
<li>CHIAMATE EROTICHE: <a style="font-size: 15px;" href="tel:0906.906.901" data-track-content="" data-content-name="0906906901" data-content-piece="www.raccontierotici24.it"> 0906.906.901</a> A 0,99 CHF AL MINUTO</li>
</ul>
<p>Vuoi spendere di meno?</p>
<p>Componi il numero <strong><a href="tel:0689083867" data-track-content="" data-content-name="0689083867" data-content-piece="www.raccontierotici24.it">06.890.83.867</a>&nbsp;</strong>e ascolta il messaggio gratuito, risparmi fino a 50 centesimi di euro al minuto.</p>
<p><a href="tel:0689083867"><img class="alignnone size-full wp-image-101" style="display: block; margin-left: auto; margin-right: auto;" src="//www.raccontierotici24.it/wp-content/uploads/2015/08/mature-al-telefono-con-carta-di-credito.jpg" alt="mature al telefono con carta di credito" width="687" height="271" /></a></p>
<p>Mi guard&ograve; porgendomelo e mi disse semplicemente "chiama se vuoi godere veramente", null&rsquo;altro. Devo essere sincera all&rsquo;inizio mi sembro uno sbruffone, quella sera nei "giochi di gruppo" non lo avevo valutato in maniera ottima, anzi. Lo chiamai pi&ugrave; per curiosit&agrave; che per altro e lo feci dopo averci pensato per qualche giorno. La ragione che mi convinse fu che un "sesso peggiore" di quello che stavo facendo con mio marito non poteva esistere, perci&ograve;... tanto valeva provare. Al telefono concordammo un appuntamento per la sera in un B&amp;B vicino, non si parl&ograve; di null&rsquo;altro, ma mi diede l&rsquo;impressione che "stesse aspettando" la mia chiamata, e questo suo atteggiamento m&rsquo;incurios&igrave; ancor di pi&ugrave;. La mia curiosit&agrave; trovo sfogo nel momento in cui lo vidi nella stanza.</p>
<p>Mi attendeva coperto da un asciugamano e da null&rsquo;altro. Doveva aver fatto la doccia e aveva ancora i capelli bagnati, sapeva gi&agrave; che mi "sarei donata" a lui e il suo atteggiamento non faceva nulla per nasconderlo. Non ebbi il tempo di entrare che dopo un rapido "ciao" gi&agrave; mi aveva messo la lingua in bocca, non aveva messo in preventivo un mio rifiuto, sapeva che quella sera mi avrebbe scopato.</p>
<p>Io avevo un vestitino corto, avevo scelto un "abbigliamento sexy" ma non provocante, anch&rsquo;io pensavo che quella sera ci sarebbe stato del sesso, ma avevo preventivato un approccio "pi&ugrave; morbido". Lui invece non aveva nulla di soft, mi baci&ograve; e mentre lo faceva le sue mani, mi presero da dietro ghermendo il mio culo e mi alzarono, sempre baciandomi mi port&ograve; sul letto e inizi&ograve; a spogliarmi. Non erano passati 5 minuti dal mio ingresso nella stanza che mi erano rimaste solo le autoreggenti e avevo il suo cazzo in bocca.</p>
<p>Non aveva parlato mi aveva semplicemente spogliato e infilato la sua asta tra le mie labbra. L&rsquo;atteggiamento che stava tenendo era paradossale ma eccitante, mi stava "trattando da troia" e la cosa buffa era che mi piaceva. Mi aveva scopato in bocca violentemente poi improvvisamente si era fermato, c&rsquo;erano state pochissime parole tra noi, lui sembrava sapere esattamente cosa fare e soprattutto come farlo.</p>
<p>Adesso ad esempio aveva terminato con la mano, e aveva sistemato il suo cazzo all&rsquo;apertura della mia umida fessura, guardandomi dritto negli occhi mi penetrava dolcemente per qualche centimetro, le sue mani erano sulle mie tette e facevano seguire l&rsquo;azione di penetrazione con una "pressione progressiva" sui capezzoli, appena mi lamentavo ritraeva il cazzo.</p>
<p>Era una situazione infernale, a me non &egrave; piaciuto mai il dolore fisico e per questo fuggo da tutto quello che &egrave; il "sesso BDSM", ma la situazione era demoniaca. Volevo essere penetrata, ma per farlo dovevo subire il dolore che le sue dita m&rsquo;infliggevano, mi aveva messo in una posizione limite: per avere il piacere dovevo subire il dolore. Sentivo gli umori uscire dalla mia figa e bagnare le lenzuola, stavo provando delle sensazioni uniche e mai avute fino allora. Sono per natura una "pluriorgasmica", e mi stava portando a godere senza soluzione di continuit&agrave;. Fin&igrave; quel gioco e si dispose tra le mie gambe, avevo i capezzoli che mi dolevano, ma ero in estasi.</p>
<p>Sentivo adesso la sua lingua sul mio clitoride, alternava veloci leccate con delle succhiate profonde, non riuscivo a controllarmi. Lui non "smetteva di giocare" con il mio corpo. Era in ginocchio tra la mia figa, le mie gambe gli sfioravano la testa, e mentre lui succhiava erano pervase da un tremore incontrollabile, appena ci&ograve; accadeva lui si bloccava. Mi guardava e mi diceva "se tremi non lecco, concentrati a farle rimanere ferme".</p>
<p>Era se possibile una "tortura" ancor pi&ugrave; perversa di quella che aveva attuato prima, dovevo fare uno sforzo per bloccare il tremore, ma esse erano animate da una "vita indipendente", che proveniva dal piacere che il mio corpo stava ricevendo.</p>
<p>"Il piacevole supplizio" and&ograve; avanti per molto tempo, persi il conto delle volte che avevo raggiunto l&rsquo;orgasmo, avevo solamente la certezza che sotto di me le lenzuola fossero intrise dei miei umori, che continuavano a sgorgare dalla mia figa. Dopo quelle che mi sembrarono ore passate tra le mie gambe, Sandro cambi&ograve; di nuovo "gioco". Si mise steso sulla schiena, il suo cazzo si ergeva dritto, e mi "ordin&ograve;" di impalarmi.</p>
<p>Voleva che muovessi solamente il bacino e che strusciassi il clito sul suo corpo, nel frattempo lo sentivo dentro di me nella sua immensa turgidezza. Ero io che dovevo muovermi piano questa volta, ma lui dettava "il ritmo" e mi fermava ogni volta che si accorgeva, che stavo raggiungendo l&rsquo;orgasmo. Per una volta provai a "cavalcarlo", ma la sua mano mi strattono per i capelli facendomi provare dolore, e facendomi capire che non potevo sfuggire ai "suoi ordini".</p>
<p>Mi sentivo una "vacca in calore" e continuavo a godere, ero stanchissima. Lui dovette accorgersene perch&eacute; non riuscivo pi&ugrave; a "tenere il ritmo", mi disse di smettere. Prese la mia testa e la port&ograve; sul cazzo, venne nella mia bocca e io non ne lasciai "sfuggire" neppure una goccia. Lui and&ograve; a fare la doccia io invece presi sonno, al mio risveglio non c&rsquo;era pi&ugrave;.</p>
<p>Sul letto un bigliettino "ci vediamo tra un mese troia, e vedi di &hellip;depilarti la figa".</p>