<p>Sono un ragazzo di 23 anni e da qualche anno ho scoperto tutta la bellezza e l'erotismo del sesso. </p>

<p>Da quando ho vissuto la mia prima esperienza sessuale ho capito di non poter fare a meno del sesso. </p>

<p>Infatti da quel momento in poi sono sempre alla ricerca di trasgressione e seduzione. Ma ho notato come da qualche mese i miei desideri si siano spinti oltre: questo perché ho avuto diversi rapporti con ragazze della mia età e tutti, ad un certo punto, finivano per essere monotoni e poco frizzanti. Ecco perché iniziai a guardare con desiderio donne esperte e anche di una certa età che sapevo avrebbero potuto farmi vivere tutta la bellezza del sesso. </p>

<p>Provavo sempre più il desiderio di avere un'esperienza sessuale piccante con una donna matura ma non avrei mai avuto il coraggio di avvicinarne una. Sono sempre stato pronto a lasciarmi andare a momenti di piacevole erotismo ma pensavo di non poter mai soddisfare questo mio desiderio lussurioso. </p>

<p>Ma il mio racconto incestuoso è assolutamente hot in quanto riguarda le esperienze trasgressive vissute con una persona della mia famiglia. Già perché da qualche tempo notavo con particolare interesse il modo di porsi di mia zia, una seducente donna di 40 anni. Ho sempre avuto modo di vedere come lei fosse in grado di attirare le sue attenzioni su di sé anche per via di un fisico notevole, a volte anche meglio di molte altre ragazze. </p>

<p>Ecco perché già da qualche tempo, soprattutto durante il periodo estivo mi lasciavo andare a qualche sguardo hot e avevo modo di eccitarmi. Infatti non riuscivo a fare a meno di guardarle il lato b che quando indossava le gonne era un qualcosa di spettacolare. Senza dimenticare anche un seno sodo e da sogno che ogni qual volta si piegava per le pulizie finiva per essere un oggetto del desiderio per me. Posso dire che da allora ho scoperto che con mia zia avrei desiderato avere qualche rapporto intimo ma non avevo il coraggio di avanzarle una proposta. Tutto di lei mi faceva impazzire, anche perché sapeva porsi in un modo seducente e soprattutto il suo look era assolutamente provocante. </p>

<p>Il mio racconto incestuoso ha origine da una domenica pomeriggio di fine estate. Lei era particolarmente sensuale grazie ad una delicata abbronzatura e ad un vestitino che in quel pomeriggio decise di indossare per via del caldo. Appena arrivò le sorridevo e scherzavo con lei e non potetti fare a meno di notare come si instaurò fin da subito una certa complicità. Mentre eravamo seduti nel giardino a goderci un pomeriggio in famiglia, io ero seduto più lontano rispetto agli altri e guardavo le sue gambe accavallate sperando che prima o poi mi desse modo di guardare anche in mezzo. I miei sguardi diventavano sempre più eccitati e desiderosi di lasciarsi andare a qualcosa di molto erotico. </p>

<p>La mia voglia aumentava e sentivo il mio pene eccitarsi mentre ammiravo le sue splendide gambe lisce e i suoi piedi eleganti. Ma all'improvviso mentre la guardavo senza minimamente ascoltare i discorsi che faceva con altri parenti, notai come iniziò a fissarmi. La cosa inizialmente mi imbarazzò molto e così fui portato subito a cambiare traiettoria con lo sguardo, ma appena mi tornai a voltare vidi come lei mi sorrideva ed iniziava ad accarezzarsi le gambe toccandole con delicatezza.</p>


<p>Questa cosa non passò inosservata per me e perciò iniziai a capire che forse lei aveva inteso quella che era la mia eccitazione a guardarla. Lì per lì non ci fu molto, se non qualche sguardo malizioso e qualche sorriso ripetuto. Il pomeriggio terminò e la zia decise di andar via ad un certo punto per andare a prendere i miei cugini ad una festa.</p> 

<p>Aspettavo il momento del saluto per sentire il suo profumo e per poter avere un contatto, fosse anche stata solo una semplice stretta di mano. Così non fu in quanto colsi l'occasione per accompagnarla a prendere delle buste nella cucina e lei mi salutò con un bacio sulla guancia molto affettuoso e con la mano sfiorò molto delicatamente le mie parti intime. Dopo un sorriso molto eccitante si stampò sul suo volto e io mi sentivo bloccato e nello stesso tempo assolutamente desideroso di possederla. Ma mi rendevo conto di come questo sarebbe stato assolutamente difficile e mi avrebbe esposto ad un vero e proprio scandalo in famiglia. Appena fui a casa pensavo e ripensavo a quello che era successo ma soprattutto non potevo fare a meno di pensare a quelle curve mozzafiato del suo corpo che emergevano dal vestitino che in quel pomeriggio caldo di fine estate indossava. </p>

<p>Proprio mentre ero a letto, preso da questi pensieri erotici, mi arriva un sms da mia zia. Appena lessi il suo nome sul mio cellulare i miei desideri piccanti schizzarono alle stelle: mia zia mi chiedeva se il pomeriggio successivo avevo possibilità di andare a casa sua per via di alcuni problemi al suo pc e dell'urgenza di averlo a disposizione per lavoro. Già qualche tempo fa mi capitò di andare a casa sua per risolvere alcuni problemi al pc, perciò la cosa finì per non farmi scattare nessuna particolare scintilla.
Il lunedì pomeriggio seguente a quella domenica eccitantissima, mi recai a casa dei miei zii. Passando nel parcheggio condominiale feci caso che non c'era la macchina di mio zio quindi immaginai di trovarmi solo in casa con mia zia e la cosa non mi sarebbe affatto dispiaciuta. </p>

<p>Bussai al campanello e nel momento in cui sentii il rumore della serratura provai un forte desiderio sessuale che ero consapevole di dover trattenere in quanto immaginavo fossero in casa anche i miei due cugini. La porta si aprì ma mia zia si nascondeva dietro di essa non dandomi così modo di vederla. Io entrai e mi fermai poco dopo la porta di ingresso per togliermi la felpa visto che provavo una sensazione di calore legata al clima e all'eccitazione. Non appena mi girai ebbi modo di vedere come mia zia indossasse una camicetta da notte completamente trasparente. La cosa più eccitante che abbia mai visto anche perché non indossava biancheria intima: mia zia era completamente nuda, non aveva né reggiseno né mutandine. Non aprii bocca ma in quel momento l'unica cosa che riuscivo a fare era guardarla e provare un immenso desiderio di possederla. Le chiesi come nulla fosse quale problema avesse avuto con il pc e lei non mi diede modo di aggiungere altro che subito iniziò a venirmi vicino e ad accarezzarmi le parti intime con grande delicatezza. Il mio pene si induriva sempre di più e vedevo che lei apprezzava questa cosa. </p>

<p>Avevo solamente voglia di fare sesso con lei e questa voglia non era pari a quella avuta in passato anche per ragazze dell'età mia o poco più grandi.v 

<p>Così finì per spingermi in maniera molto provocante sul divano del salone, proprio quello dove con i parenti ci riunivamo durante le feste natalizie. Il solo pensiero di essere lì con lei completamente nuda mi faceva eccitare ancora di più. Lei a bassa voce mi chiedeva come mai da tempo la guardassi con gli occhi pieni di voglia di sesso e soprattutto voleva sapere se mi piaceva effettivamente il suo corpo. Con un filo di voce provai a rispondergli e non ricordo neanche di preciso cosa le dissi: so soltanto che lei iniziò a sfilarsi quella camicetta in modo erotico. Si trovò così completamente nuda dinanzi a me non riuscii a fare a meno di abbassarmi il pantalone. La cosa a lei era molto gradita in quanto mi disse che non aspettava altro e che da tempo provava una notevole eccitazione nei miei confronti. Ammise anche di essersi masturbata a volte pensando al mio pene e a cosa sarebbe potuto essere il sesso insieme. Mi abbassò con forza gli slip e mi ritrovai con il mio pene duro ed assolutamente eccitato completamente scoperto. Così lei iniziò ad accarezzarmelo e successivamente si avvicinò per leccarlo. </p>

<p>In quel momento godevo come mai successo prima d'ora e io mantenevo la sua testa che andava su e giù per un'esperienza di sesso orale indimenticabile. Furono dei minuti assolutamente piacevoli finché lei non smise e io avevo ancora più voglia di fare sesso. Fu così che lei per un attimo andò in camera da letto: mentre camminava le guardavo il fondoschiena da sogno che aveva. Portò un preservativo e mentre lo aprivo e me lo mettevo lei si poggiò sul divano ed iniziò a toccarsi mentre guardava il mio pene eccitato. </p>

<p>Appena misi il preservativo le andai incontro e senza neanche farla spostare dal divano misi il mio pene nella sua vagina bagnata e del tutto eccitante. Iniziammo così a fare sesso e fu qualcosa che mai potrò dimenticare. Lei urlava e raggiunse così l'orgasmo ma la sua voglia di sesso non era placata, così come la mia. Avevamo voglia di spingerci ancora oltre e così la girai ed iniziai a penetrarle l'ano, proprio come le piaceva. Sentivo che mentre la penetravo lei si toccava e provava un'eccitazione unica. </p>

<p>Stemmo un'ora e mezza in quel salone che per quel pomeriggio divenne un nido di lussuria e di trasgressione.</p>

<p>Componi il numero&nbsp;&nbsp;<strong><a href="tel:0689083867" data-track-content="" data-content-name="0689083867" data-content-piece="www.raccontierotici24.it">06.890.83.867</a>&nbsp;</strong>e ascolta il messaggio gratuito, risparmi fino a 50 centesimi di euro al minuto.</p>
<p><a href="tel:0689083867"><img class="alignnone size-full wp-image-101" style="display: block; margin-left: auto; margin-right: auto;" src="//www.raccontierotici24.it/wp-content/uploads/2015/08/mature-al-telefono-con-carta-di-credito.jpg" alt="mature al telefono con carta di credito" width="687" height="271" /></a></p>