<p>Quando mio marito ha allungato la mano per darmi un pacchetto mi &egrave; sembrato un semplice gesto carino. Avrei voluto aprirlo subito ma lui ha insistito che lo aprissi una volta arrivata in albergo al mare.</p>
<p>Durante il viaggio sono stata pi&ugrave; volte sul punto di aprire il regalo. Conteneva qualcosa da indossare, ma per evitare il rischio di trovarmi nel mezzo del treno affollato con un completino intimo in bella mostra, ho resistito. Gli ho chiesto se era impazzito. Avevo appena aperto il regalo trovandoci un bikini microscopico.</p>
<h2 style="text-align: center;"><strong>Chiama subito una moglie vogliosa: <a href="tel:899.89.82.88" data-track-content="" data-content-name="899898288" data-content-piece="www.raccontierotici24.it">899.89.82.88</a></strong></h2>
<div class="uk-grid-divider uk-child-width-expand@s" uk-grid><div><img class="uk-align-center uk-margin-small-bottom" src="/storage/italy.png" alt="svizzera" width="26" height="17" /><p class="uk-text-center">CHIAMATE EROTICHE MATURE: <a style="font-size: 15px;" href="tel:899.37.00.32" data-track-content="" data-content-name="899370032" data-content-piece="www.raccontierotici24.it">899.37.00.32</a></p></div>
<div><img class="uk-align-center uk-margin-small-bottom" src="/storage/chicon.png" alt="svizzera" width="26" height="17" /><p class="uk-text-center">CHIAMATE EROTICHE MATURE: <a style="font-size: 15px;" href="tel:0906.906.666" data-track-content="" data-content-name="0906906666" data-content-piece="www.raccontierotici24.it">0906.906.666</a> A 0,99 CHF AL MINUTO</p></div></div>
<p>Il reggiseno no, era di dimensioni normali ma il tanga era talmente minuscolo da costringermi ad una rasatura completa del mio pube. Lui rideva come un matto e poi mi ha detto che sarebbe stato contento se l'avessi indossato e gli avessi inviato qualche foto delle espressioni degli uomini che mi avrebbero guardato. Gli ho detto che poteva scordarselo e ho messo gi&ugrave;. Per&ograve; l'immagine di tutti quegli occhi che mi avrebbero fissato e desiderato mi aveva gi&agrave; eccitata da morire.</p>
<p>Cos&igrave; decisi di prendere appuntamento dall'estetista dell'albergo. Il monte di venere totalmente liscio mi dava una sensazione di piacevole vulnerabilit&agrave;. Il seno sodo, il sedere ben rinforzato dagli allenamenti del mio istruttore e le gambe lunghe mi assicuravano un'ottima figura sulla spiaggia. Il mio pudore invece era rigido, fuori allenamento per cos&igrave; dire. Ne ebbi la prova una volta indossato il costume. Bianco, copriva perfettamente la mia terza di seno ma con un rettangolino copriva a stento le labbra del mio sesso. Dietro solo uno string sormontato da un triangolino puramente decorativo. Se era questo che voleva mio marito, questo avr&agrave;.</p>
<p>Mi assicurai che il cellulare fosse carico e andai a dormire presto. Si prospettava una giornata intensa. Cercai subito un ombrellone lontano dai bambini e sistemai le mie cose. Ereader, crema solare, libro, rivista, occhiali da sole e cellulare. Tolsi il copricostume senza guardare nessuno e mi stesi sulla sdraio coperta da enormi occhiali da sole. Fioccarono le occhiate furtive sul mio costume e decisi di rifugiarmi in mare. Quello che non sapevo era che il tessuto in microfibra del mio costume sarebbe diventato completamente trasparente una volta bagnato.</p>
<p>La mia fica era visibile da tutti su una spiaggia affollata. Ero praticamente nuda e non me n'ero andata. Se &egrave; questo che voleva mio marito, questo avrebbe avuto! Mi ritrovai davanti un uomo che non sapevo se fosse simpatico ma di sicuro bello e con un fisico imponente. Senza lasciargli il tempo di parlare gli chiesi se volesse scattare una foto con me per mio marito. Rimase di stucco ma una volta raccontata la storia accett&ograve;.</p>
<p>Il risultato furono due foto in cui questo meraviglioso uomo teneva un braccio sulle mie spalle e le mie labbra gonfie si vedevano chiaramente attraverso quella striscetta di tessuto che per qualche motivo avevano chiamato costume da bagno. L'uomo rise guardando le foto e si limit&ograve; a dirmi di prendere la borsa per andare in camera sua. Accettai senza nemmeno rispondere. Una volta in camera andai in bagno per sistemarmi e controllare se mio marito avesse visto le foto. Le aveva viste, aveva inviato i suoi complimenti e un invito a godermi le vacanze pi&ugrave; che potevo.</p>
<p>Ero sempre pi&ugrave; eccitata e uscii dal bagno completamente nuda. Quel meraviglioso sconosciuto mi fiss&ograve; per un attimo, poi mi baci&ograve;. Le sue mani mi spinsero sul letto e io non seppi fare altro che aprire le gambe per accoglierlo. Si mise su di me e fece scivolare con delicatezza il suo sesso nel mio. Da quel momento fu solo piacere. Prese a scoparmi con foga, si sentiva il rumore dei suoi colpi come se fossero schiaffi sulla mia fica. Si ferm&ograve; solo quando fu sul punto di arrivare.</p>
<p>Usc&igrave; e mise il suo uccello davanti al mio viso. Mossi la testa per regalargli lo stesso piacere che aveva dato a me. Restammo in silenzio per un po' poi gli feci leggere gli ultimi messaggi ricevuti.</p>
<div class="uk-grid-divider uk-child-width-expand@s" uk-grid><div><p class="uk-text-center">TELEFONO EROTICO ZITTO E GODI: <a href="tel:899.84.85.97">899.84.85.97</a></p></div>
<div><p class="uk-text-center">TELEFONO EROTICO CON CARTA DI CREDITO: <a style="color: #ff0000;" href="tel:06.890.838.67">06.890.838.67</a></p></div>
<div><p class="uk-text-center">TELEFONO EROTICO BASSO COSTO: <a href="tel:899.00.33.65">899.00.33.65</a></p></div></div>
<p>Prese il mio cellulare e lo pos&ograve; sul letto. Riprese coi suoi baci e con le sue mani che piano si infilano in ogni mio anfratto. Ero di nuovo eccitata da morire. Inizi&ograve; a leccarmela, ero in paradiso. Chiusi gli occhi per godermi quella meravigliosa lingua, poi un click me li fece riaprire. Aveva scattato una foto per mio marito mentre era con la lingua tra le mie gambe. Tremavo dal piacere e dalla preoccupazione. Stavo distruggendo il mio matrimonio per un momento di follia. In quel preciso istante sentii la mia fica spalancarsi e il mio corpo diventare di burro.</p>
<p>Stacc&ograve; la lingua e infil&ograve; il suo cazzo a met&agrave;. Altro scatto, altro invio. Pos&ograve; il cellulare e riprese a scoparmi. Nel frattempo arrivarono diversi messaggi ma li ignorai. Senza uscire si ferm&ograve; e lesse le risposte mio marito e ripose il cellulare. Si limit&ograve; a dirmi che erano ordini del mio uomo e lui doveva eseguirli. Uscito dalla fica si diresse verso il culo, lo infil&ograve; per met&agrave; e part&igrave; la seconda foto. Anche stavolta si ferm&ograve; prima di arrivare ma non si diresse verso la mia bocca, arriv&ograve; copiosamente sulla mia fica. Part&igrave; l'ennesima fotografia. Trascorsi tutta la settimana passando dal suo letto alla spiaggia e dalla spiaggia al mio letto.</p>
<p>Mio marito ebbe un book fotografico da fare invidia ad una pornostar ed io mi sentii totalmente libera di essere me stessa. Da quel momento i periodi di libert&agrave; dalla vita di coppia divennero degli appuntamenti fissi e il mio guardaroba si riemp&igrave; di abbigliamento sexy e mio marito dovette procurarsi un nuovo hard disk in cui salvare le foto delle mie avventure. Tutto per un semplice pacchetto regalatomi da mio marito.</p>