<p>Quando mi rivolsi al mondo del bondage e del sado maso ero un uomo molto insicuro, non solo nella vita ma anche al chiuso delle camere da letto tra le lenzuola, un uomo che non riusciva a godere del proprio corpo e che spesso e volentieri raggiungevo il piacere solamente con pratiche di autoerotismo, in poche parole con le vecchie seghe, seghe che però servivano solamente a scaricare il mio corpo, ma non certo a farmi raggiungere quella tranquillità mentale e interiore che ricercavo, e che sapevo mi avrebbe soddisfatto. </p>

<p>Poi un mondo si è aperto dinanzi ai miei occhi, un mondo che era identificato da quattro semplici lettere, BDSM. Bondage e sado masochismo. Avvenne per caso una notte, navigando sulla grande rete, come facevo di solito quasi ogni sera in cerca di emozioni, sui siti erotici. Una navigazione solitaria effettuata nel chiuso della mia piccola camera, mentre facevo attenzione a non svegliare i miei genitori, con il quale ancora abito per i soliti problemi economici che assillano le nuove generazioni, in questo nostro magnifico bel paese. </p>

<p>Il sito era il mio sogno, con filmati che non facevano altro che sottolineare come molti nel mondo moderno si eccitano con il dolore e le umiliazioni impartite, da padroni e mistress senza scrupolo in camera da letto. Pratiche che ormai facevano parte del mio modo di pensare, ma che ancora non ero riuscito a mettere in pratica nel reale. Rimasi estasiato tutta la notte guardando video erotici e leggendo racconti particolari, e desiderando con tutto me stesso di essere uno di quei schiavi che servono le loro altere e superbe regine, guadagnando da loro solamente dolore e sofferenza, presupposto basilare per farmi eccitare e raggiungere il godimento corporale. </p>

<p>Mi feci coraggio e poco prima dell’alba mandai qualche mail per avere un appuntamento da qualcuna di loro, purtroppo nessuno padrona rispose quella sera, cosi come nessuna mail arrivo nella mia casella di posta elettronica nelle settimane a venire. Non riuscivo a capire perché, ma probabilmente la mancata di attenzione che suscitavo era da ricondurre all’inesperienza, che trapelava dalle poche righe che avevo scritto come presentazione. </p>

<p>Cercai per questo di riconfigurare la mia presentazione, mettendoci più cura in quanto scritto e allegando a un annuncio qualche foto a corpo intero. Sicuramente colpii nel segno, attirando quasi subito l’attenzione di una coppia che si presentava come una coppia con entrambi dominanti.</p>

<p>Non avevo pensato a questa variabile, la mia idea era di servire una donna, ma soffermandomi sul pensiero di una coppia la cosa mi attirava in un recesso luogo della mia mente, sarebbe stata un’esperienza totalizzante "servire" una coppia, anche se non posso nascondere che mi preoccupava un po’ avvicinarmi "intimamente" a un uomo.</p>

<p>Era la mia prima occasione e non volevo perderla, per questo allacciai immediatamente rapporti virtuali con essi. Ci fu qualche settimana in cui molte mail furono inviate, vollero sapere tutto di me, dalle mie esperienze pregresse in questo bellissimo mondo al mio stato civile, dal mio peso alla grandezza del mio attrezzo, ero sicuro che stessero valutandomi attentamente e feci di tutto per essere il più sincero possibile nelle mie risposte. Alla fine riuscì a strappare loro un appuntamento, sarebbe stata la mia prima volta reale da schiavo. </p>

<p>Concordammo l’appuntamento per il sabato successivo a casa loro, abitavano a una cinquantina di chilometri da casa mia, e mi avevano detto che avevano a disposizione una bella stanza attrezzata con tutti i gingilli relativi al sadomaso. I giorni che mi separavano all’appuntamento furono trascorsi in un misto di eccitazione per il mio nuovo ruolo di giocattolo sessuale, e la paura per quanto mi sarebbe stato riservato in quella stanza al chiuso dagli sguardi indiscreti, entrambe le cose mi lasciavano praticamente di fatto in uno stato di eccitazione semi permanente. </p>

<p>Arrivo il giorno e già dalla mattina mi preparai con cura, mi avevano detto di andare a casa loro senza indossare l’intimo, e dovetti abbandonare gli slip nel bagno di un area di servizio dell’autostrada, visto che non potevo uscire di casa senza. Arrivai però puntuale come un orologio svizzero, e rimasi qualche minuto a guardare dall’esterno la bella villa dove abitavano, villa che sarebbe stata per quella sera la mia prigione volontaria.</p>

<p>Suonai e attesi che mi aprissero la porta, a farlo fu lei una donna di una quarantina d’anni veramente interessante sotto il punto di vista fisico. Era bionda con un bel seno prorompente fasciato da un top nero ed aderente che faceva risaltare i capezzoli, un bel viso da bambolina con capelli biondi e lunghi fin sulle spalle, e due cosce che quella sera erano fasciate da una gonna di pelle anch’essa nera, e esaltate da un paio di scarpe con il tacco molto alto. </p>

<p>Mi allungo la mano per salutarmi, e mentre lo faceva mi trapasso con lo sguardo, presumo che venne lei ad aprire perché era lei che doveva accettarmi o meno. Lo fece. Mi disse di entrare e mi introdusse in salotto, dove trovammo il suo uomo. Era seduto comodamente su una poltrona di cuoio, e vedendomi entrare non si scomodo per nulla, alzo lo sguardo per una veloce occhiata, e poi con un tono di voce gentile, ma che al contempo non ammetteva repliche mi disse "in ginocchio".</p>

<p>Sapevo che non ci sarebbero state smancerie, perché per mail mi avevano detto che questo era il loro modo di agire, ma non mi aspettavo un trattamento del genere, stetti qualche secondo a pensarci su, fino a quando non senti la voce della donna dire: "se non vuoi puoi andare", non ci pensai minimamente, e immediatamente le mie ginocchia raggiunsero il freddo marmo del pavimento. </p>

<p>Iniziai in quella posizione la mia serata, una serata che mi vide un tuttofare sessuale, a cui senza soluzione di continuità fu imposto di servire in ogni modo i miei nuovi padroni. La mia lingua fu richiesta prima per pulire le scarpe dei miei padroni, capivo che non era il dolore fisico che essi all’inizio ricercavano, ma solamente l’annullamento totale della mia volontà di maschio. Dovevo diventare un servo a loro disposizione, dimenticando quanto la società nel passato mi aveva insegnato, volevano il mio asservimento totale, cosa che io ambivo a fare con tutto me stesso. Li osservavo sottocchio mentre li leccavo, sui loro sguardo il ghigno di chi sapeva di aver acquistato un giocattolo sessuale, che probabilmente li avrebbe soddisfatti per i mesi a venire.</p>

<p>Non ci fu una parte difficile in quella serata, ero troppo motivato a superare le prove e abbastanza concentrato da voler sentire le sensazioni che derivavano dal farlo, per sentire il dolore delle frustate o il fastidio dei piccoli pesi sui coglioni che mi obbligarono a mettere quasi da subito, e che dovetti tenere per tutta la serata. Assaporai ogni attimo, anche quando il mio padrone desidero la mia lingua sul suo cazzo, non mi ero mai avvicinato al pene di un uomo ma lo feci sapendo che sarebbe stata quella la strada da percorrere per raggiungere il godimento. Lo feci, con inesperienza ma lo feci, la mia bocca accolse quell’asta turgida e dura come il marmo, la mia lingua fece di tutto per dare il meglio di se, la mia testa si concentro per succhiarlo come solo una troia sa fare.</p>

<p>Fui legato su una croce di sant’Andrea e frustato con un piccolo gatto a nove code, mi avevano imposto di contare ogni colpo, e anche se le frustate non mi portavano tantissimo dolore era moltissimo il piacere che derivava dalla situazione che stavo vivendo. Ambivo al dolore e lo facevo volontariamente, guardavo negli occhi il mio padrone mentre torturava la mia pelle, e desideravo che non smettesse mai.</p>

<p>Fui obbligato a leccarlo mentre a pecora la sua donna giocava con il mio culo, scoparono sulla mia faccia con la mia lingua che si ritrovava alternativamente a leccare il cazzo turgido o la fessura bagnata. Mi umiliarono a parole e con i gesti, si fecero servire a tavola mentre ero nudo e con i pesi applicati, era una tortura muovermi per portare loro i piatti, ma lo facevo senza fiatare.</p>

<p>Alla fine della serata mi usarono da cesso per scaricare le loro vesciche, inondandomi insieme con la loro orina, era l'apoteosi delle umiliazioni, una pioggia dorata che serviva a farmi capire come io per loro non ero null'altro che un bagno a loro disposizione.</p>

<p>Alla fine della serata mi guardarono soddisfatti di ciò che avevo fatto per loro, e prima di andare mi diedero il permesso di godere con una sega. Facendolo e guardandoli negli occhi capii che non era la solita sega che mi facevo al chiuso della mia camera, avevo la consapevolezza che nonostante fossero sempre le mie mani a portarmi al godimento, era un godimento che mi ero guadagnato con il dolore e la sofferenza, il grande schizzo che dopo qualche secondo porto fuori dal mio corpo la sborra, non fece altro che sottolineare il concetto. </p>

<p>Mi obbligarono a pulire il pavimento e mi congedarono senza neppure salutarmi, mi vesti in sala mentre li sentivo finire la serata con una scopata sul comodo del loro materasso, al chiuso della camera da letto. Li invidiai, ma sapevo che non potevo ottenere di più dal mio battesimo da schiavo.</p>

<p>Da allora ci vediamo almeno una volta al mese, e cerco di soddisfarli in tutto e per tutto, questa è diventata la mia massima aspirazione. Farlo mi ha portato ad avere più equilibrio sia nel sesso che nella vita privata, per questo non posso fare più a meno del BDSM, un attività che ha letteralmente cambiato in meglio la mia vita.</p>

<h2 style="text-align: center;"><strong>Chiama subito: <a href="tel:899.89.82.88" data-track-content="" data-content-name="899898288" data-content-piece="www.raccontierotici24.it">899.89.82.88</a></strong></h2>
<p><img src="/storage/chicon.png" alt="svizzera" width="26" height="17" /> Per accedere alle chiamate erotiche dalla Svizzera componi il seguente numero:</p>
<ul>
<li>CHIAMATE EROTICHE: <a style="font-size: 15px;" href="tel://0906.906.901" data-track-content="" data-content-name="0906906901" data-content-piece="www.raccontierotici24.it"> 0906.906.901</a> A 0,99 CHF AL MINUTO</li>
</ul>
<p>Vuoi spendere di meno?</p>
<p>Componi il numero <strong><a href="tel:0689083867" data-track-content="" data-content-name="0689083867" data-content-piece="www.raccontierotici24.it">06.890.83.867</a>&nbsp;</strong>e ascolta il messaggio gratuito, risparmi fino a 80 centesimi al minuto.</p>
<p><a href="tel:0689083867"><img class="alignnone size-full wp-image-101" style="display: block; margin-left: auto; margin-right: auto;" src="//www.raccontierotici24.it/wp-content/uploads/2015/08/mature-al-telefono-con-carta-di-credito.jpg" alt="mature al telefono con carta di credito" width="687" height="271" /></a></p>