<p>Questa storia risale a quando ero poco pi&ugrave; di un giovincello sbarbato, avevo da poco finito il quinto anno delle scuole superiori e quel diploma sudatissimo era l'unica cosa che possedevo e che mi faceva sentire finalmente grande e pronto per il mondo lavorativo.</p>
<h2 style="text-align: center;"><strong>Chiama subito: <a href="tel:899.89.82.88" data-track-content="" data-content-name="899898288" data-content-piece="www.raccontierotici24.it">899.89.82.88</a></strong></h2>
<div class="uk-grid-divider uk-child-width-expand@s" uk-grid><div><img class="uk-align-center uk-margin-small-bottom" src="/storage/italy.png" alt="svizzera" width="26" height="17" /><p class="uk-text-center">CHIAMATE EROTICHE MATURE: <a style="font-size: 15px;" href="tel:899.37.00.32" data-track-content="" data-content-name="899370032" data-content-piece="www.raccontierotici24.it">899.37.00.32</a></p></div>
<div><img class="uk-align-center uk-margin-small-bottom" src="/storage/chicon.png" alt="svizzera" width="26" height="17" /><p class="uk-text-center">CHIAMATE EROTICHE MATURE: <a style="font-size: 15px;" href="tel:0906.906.666" data-track-content="" data-content-name="0906906666" data-content-piece="www.raccontierotici24.it">0906.906.666</a> A 0,99 CHF AL MINUTO</p></div></div>
<p>Io &egrave; il mio amico di banco Andrea passavamo ore ed ore a spulciare gli annunci economici, eravamo pieni di speranze e avremmo fatto chiss&agrave; cosa pur di raggranellare qualche spicciolo per trascorrere qualche ora al mare a goderci di un meritato riposo.</p>
<p>Purtroppo non erano tempi buoni e non saremmo mai potuti partire per le vacanze da soli come facevano gran parte dei nostri coetanei, pensavamo proprio di dover passare tutta l'estate al caldo di quella nostra cittadina di provincia, quando la mamma di Andrea vedendoci cos&igrave; afflitti ci fece una proposta inaspettata.</p>
<p>Ci chiese se ci sarebbe piaciuto trascorrere una quindicina di giorni in Calabria nel bungalow che aveva affittato insieme al marito, magari avremmo potuto piantare la nostra canadese accanto alla loro dimora se proprio non ci andava di trascorrere le ferie con due 'Matusa'!</p>
<p>La proposta cadde come la manna dal cielo e la mia risposta fu subito affermativa con grande gioia di Andrea al quale non pareva vero avere al suo fianco il suo migliore amico anche durante il periodo estivo.</p>
<p>Ci preparammo con entusiasmo a quella partenza anche perch&eacute; entrambi siamo appassionati di pesca e con il pap&agrave; di Andrea avevamo in programma delle pescate notturne di anguille e gamberi che ci avrebbero sicuramente fatti divertire.</p>
<p>Arrivammo in Calabria dopo qualche giorno e montammo la nostra tenda a fianco al Bungalow del signor Bruno e della signora Maria che ogni giorno preparava per noi manicaretti da far invidia a qualsiasi trattoria locale.</p>
<p>Intanto, non saltava una sera che non andavamo in spiaggia a pescare con le nostre canne nuove di zecca e il bottino che portavano al villaggio dava subito i suoi frutti perch&eacute; la Signora Maria preparava fritturine gustose che profumavano tutto il villaggio.</p>
<p>Tutto procedeva a gonfie vele fino ad una sera in cui gi&agrave; pronti per la nostra pescata serale, io avvertii un leggero mal di testa. La Signora Maria da mamma premurosa, mi tasto la fronte e preg&ograve; Andrea ed il marito di andare da soli a pesca perch&eacute; pensava avessi un p&ograve; di febbre o avessi preso troppo sole la mattina in spiaggia.</p>
<p>Ad essere sincero, il mio amico e suo padre non volevano lasciarmi solo ma io che non volevo fare da guastafeste li pregai di andare lo stesso perch&eacute; ci saremmo rifatti il giorno dopo e che il mio leggero malessere non doveva essere un impedimento.</p>
<p>La Signora Maria mi preg&ograve; di non dormire in tenda quella notte ma di sostare nella stanzetta aggiuntiva del bungalow per evitare di prendere umidit&agrave; che avrebbe potuto farmi male.</p>
<p>Io mi stesi sul letto e cercai di riposare mentre la gentilissima signora andava a preparare una camomilla nel cucinotto. Mi ero quasi appisolato quando la sentii arrivare, si sedette sulla sponda del mio letto e cominci&ograve; a chiamarmi dolcemente. Non so che mi prese ma quella sera la vedevo diversa o forse era la febbre che stava incalzando ma il minuscolo bikini che aveva indosso non mi pareva di averlo mai visto nei giorni precedenti.</p>
<p>Aveva due seni piccoli e sodi come quelli delle ragazzine gi&ugrave; al paese quando facevano le smorfiosette fuori al Bar di Nando con le loro canotte aderenti.</p>
<p>Avvertivo il profumo di quella donna che mi inebriava le narici, sentivo come se il suo corpo fremesse contro il mio ma evidentemente stavo delirando. Mi alzai di scatto dal letto, sentivo un forte rossore sul mio volto e lei avvicin&ograve; le sue labbra alla mia fronte con fare materno, per avvertire se la febbre fosse aumentata.</p>
<p>Quando lo fece sentii le sue tette premere sul mio torace e la patta dei miei calzoncini pareva volesse scoppiare. Credo di aver pensato che stavo per sentirmi male e che avevo bisogno urgente di una boccata d'aria.</p>
<p>Corsi sulla verandina e respirai profondamente ma dopo qualche attimo sentii i passi della Signora Maria che mi raggiungevano.</p>
<p>Non osavo guardarla, mi vergognavo terribilmente di quello che stavo provando e appena sentii la sua mano sul mio uccello duro la guardai come se stessi sognando e le sue parole arrivavano al mio orecchio come se fossero note provenienti da una musica celestiale.</p>
<p>Non avevo mai fatto all'amore, erano altri tempi, i ragazzi erano meno spregiudicati di quelli di adesso ed io con la mia innata timidezza certamente non contribuivo a sbloccare la situazione.</p>
<div class="uk-grid-divider uk-child-width-expand@s" uk-grid><div><p class="uk-text-center">TELEFONO EROTICO ZITTO E GODI: <a href="tel:899.84.85.97">899.84.85.97</a></p></div>
<div><p class="uk-text-center">TELEFONO EROTICO CON CARTA DI CREDITO: <a style="color: #ff0000;" href="tel:06.890.838.67">06.890.838.67</a></p></div>
<div><p class="uk-text-center">TELEFONO EROTICO BASSO COSTO: <a href="tel:899.00.33.65">899.00.33.65</a></p></div></div>
<p>Non so come successe ma in un attimo mi ritrovai tra le braccia di quella donna che mi invitava a pizzicarle i capezzoli, mi diceva di metterle la lingua tra le gambe, mi esortava a prenderla da dietro.</p>
<p>Forse era un semplice sogno, forse la febbre mi stava facendo dare i numeri so solo che quella sera accadde l'incredibile, scoprii arti amatorie e doti che non credevo di avere, quella donna sembrava assatanata, non era pi&ugrave; la dolce e amorevole mamma del mio migliore amico.</p>
<p>Facemmo all'amore pi&ugrave; volte perch&eacute; la prima volta venni subito come un pivellino, ma mi ricaricai immediatamente forse preso dall'estasi di quei momenti che sono rimasti come ricordi indelebili nella mia memoria.</p>
<p>Quella notte Andrea e il Signor Bruno tornarono tardissimo, avevano pescato una buona quantit&agrave; di pesce ed erano soddisfattissimi.</p>
<p>La Signora Maria dormiva, disse che era troppo stanca ed io ero sulla verandina a pensare quando i due pescatori tornarono. Andrea mi domand&ograve; se stessi bene, evidentemente la mia faccia doveva avere un aspetto orribile ma io avevo trascorso due ore indimenticabili anche se mi guardai bene dal confidarglielo.</p>
<p>Passai il resto della notte in tenda con Andrea ma la mattina mi svel&ograve; che avevo parlato tutto il tempo come se fossi in preda ad una forte agitazione. Pensarono tutti alle conseguenze della febbre ma io so che i miei sogni erano stati popolati da quell'essere paradisiaco che in quella serata di mezza estate aveva fatto di me un uomo.</p>
<p><strong>Vuoi chiamare, godere e spendere di meno?</strong></p>
<p>Componi il numero <strong><a href="tel:0689083867" data-track-content="" data-content-name="0689083867" data-content-piece="www.raccontierotici24.it">06.890.83.867</a>&nbsp;</strong>e ascolta il messaggio gratuito, risparmi fino a 50 centesimi di euro al minuto.</p>
<p><a href="tel:0689083867"><img class="alignnone size-full wp-image-101" style="display: block; margin-left: auto; margin-right: auto;" src="//www.raccontierotici24.it/wp-content/uploads/2015/08/mature-al-telefono-con-carta-di-credito.jpg" alt="mature al telefono con carta di credito" width="687" height="271" /></a></p>