<p>Le lame di luce iniziarono a fare capolino nella stanza, segnando l’arrivo dell’alba e la fine di una notte, una notte in cui quella che fino a dieci ore prima era la mia amante, aveva guadagnato i gradi di mia …unica schiava personale. </p>

<p>Sono un uomo sposato, ma non nascondo che il mio matrimonio ha dovuto sottostare ai miei tanti tradimenti, mi piacciono le donne, e grazie anche al mio lavoro che mi permette una certa libertà, spesso sono stato uccel di bosco al di fuori del talamo matrimoniale. Ultimamente però la mia attenzione si è diretta verso la prioritaria ricerca di una schiava, una donna scelta tra le mie tante amanti, e a cui ho proposto un allenamento intensivo allo scopo di farla diventare la mia unica e sola schiavetta personale. </p>

<p>Non volevo più tante donne, volevo solamente una cagna in calore pronta a servire il mio corpo, e a soddisfare le mie voglie anche le più indicibili. La luce dell’alba ha certificato che l’ho trovata in Marta. </p>

<p>Marta era fino a ieri una delle mie donne segrete, donna non più giovanissima ma con una carica sessuale fuori dal comune, donna conosciuta per sbaglio nel parcheggio di un centro commerciale, e che subito ha attirato la mia attenzione per la sua vivacità e per la sua spiccata propensione a comandare, visto l’incarico di Store Manager che ricopre. </p>

<p>Una storia però come tanta le altre, almeno fino ad ieri, fatta di scopate nascoste negli alberghi di periferia, e di messaggi inviati di nascosto della mia donna ufficiale. Ho scelto lei pensando a chi dovessi sottomettere, perché sapevo che la sfida sarebbe stata difficile, ma sapendo anche al contempo che in caso fossi riuscito nel mio intento, la soddisfazione sarebbe stata massima non solo per me ma anche per lei, non mi sbagliavo. </p>

<p>Marta è single vista la separazione dal suo primo e unico marito, sapevo che scopava solo con me e ho sfruttato questa sua astinenza, per iniziare un addestramento che l’avrebbe portata a desiderare spasmodicamente il mio cazzo.

<br>Ricordo ancora come qualche anno fa fui chiaro con lei, se voleva essere scopata da me doveva fare tutto quello che desideravo, sempre, comunque e dovunque. Avevo letto da qualche parte che prima della dominazione fisica è importante la dominazione mentale, e cosi iniziai prima dalla mente della mia amante. Doveva iniziare ad adorarmi e a dipendere, almeno per godere, da me, lo proposi come un gioco, fu l’inizio della sua sottomissione.</p> 

<p>A letto quando ci vedevamo la facevo morire, non ho problemi a riconoscere che la facevo godere molte volte durante i nostri incontri, farla stare ben era un passaggio importante e fondamentale per ottenere quello che avevo in mente. Piano piano iniziai a inserire alcuni ordini, piccole cose come costringerla a uscire senza intimo, o applicarsi qualche molletta da bucato alle labbra della figa, ordini che servivano a testare la sua motivazione. Rispondeva sempre ottimamente, sapeva che se non avrebbe obbedito l’avrei lasciata senza cazzo, e non voleva rischiare un astinenza che gli avevo fatto già provare altre volte, e che la privava dal godimento corporale che gli fornivo. </p>

<p>Era un allenamento continuo e costante, un allenamento che gli stava facendo percorrere la strada dell’asservimento totale. La feci uscire con qualche ortaggio dentro di se, gli vietai l’intimo dicendogli che la mia figa non doveva essere "ristretta" dagli slip ma doveva "prendere aria", la chiamavo in mezzo alla notte e la facevo masturbare, vietandogli severamente di raggiungere il godimento, tutto serviva per fare capirgli che ero io a comandare e decidere. </p>

<p>Due settimane fa raggiunsi la consapevolezza che era diventata mia, esclusivamente mia, solamente mia, potevo inserire il dolore, quello vero, nell’allenamento, e feci allora il passo successivo. Grazie a uno dei tanti sexy shop presenti sulla grande rete, ordinai a suo nome una frusta, un frustino, quattro pesi, qualche corda e due candele. Una spesa di qualche centinaia di euro, una spesa che mi avrebbe fatto capire se ci avevo visto giusto. </p>

<p>L’avevo avvertita che sarebbe arrivato un pacco a casa sua, gli imposi di lasciarlo chiuso e di aprirlo solamente in mia presenza. Cosi fece. Vidi in video chiamata l’eccitazione che la prese quando gli diedi ordine di scartare il pacco, un eccitazione che per sua stessa ammissione gli portò un immediato orgasmo tra le cosce, sapeva cosa sarebbe successo, e io sapevo che la cosa gli piaceva. </p>

<p>Gli imposi che non ci saremmo più sentiti per le due settimane successive, sarebbe rimasta in attesa dei miei ordini, gli comunicai solamente che sarebbe dovuta venire nel nostro albergo quando gli lo avrei ordinato, portando gli attrezzi che gli avevo donato. Non gli nascosi che avrebbe sofferto, sarei stato duro con lei e avrebbe capito cosa significa guadagnarsi il godimento con la sofferenza. </p>

<p>La scelta era sua, io sarei rimasto in hotel ad attenderla, se non sarebbe venuta mi avrebbe perso, se invece lo avrebbe fatto avrebbe dovuto portare la sua motivazione a soffrire, e sarebbe diventata al contempo la mia unica schiava sessuale. Venne. </p>

<p>Arrivò in perfetto orario, io ero già in stanza quando lei fece squillare il mio cellulare avvertendomi che era giù. L’hotel è un B&B che avevamo usato altre volte, e che fidandosi ci lasciava soli, io avevo le chiavi visto la fiducia di cui godo con il proprietario, aprii per questo il portone e la vidi arrivare. Aveva come al solito la sua solita aria di sicurezza, ma tra le mani reggeva una borsetta da viaggio, era venuta e aveva portato gli "attrezzi", aveva accettato la sfida.</p>

<p>Non la salutai con il solito bacio, dovevo far capire lei che il nostro rapporto era cambiato, quella sera avrebbe lasciato il suo posto di amante, per diventare una serva sottomessa al suo unico padrone. Fui duro nella voce quando gli ordinai di spogliarsi, e fu ancora più duro quando gli imposi di succhiarmi, la presi in bocca con forza, tenendo la sua testa con le mani, e scopandola brutalmente tra le labbra. Non era la sera della dolcezza, era la sua prima notte di dolore. Marta capi che il rapporto era cambiato e mi accontento, fu disponibile e asservita, aveva accettato il suo ruolo.</p>

<p>Mi fermai, era ancora presto per venire e non lo volevo fare certo dentro la sua bocca, la feci girare e la bendai, stava per iniziare ufficialmente la sessione di addestramento. Nell’ora successiva ci diedi dentro con la frusta, nella stanza si sentiva solamente il sibilo dell’attrezzo che fendeva l’aria, e il colpo che seguiva sul corpo di Marta, iniziai lentamente e aumentai i colpi sempre di più, alla fine la schiena della mia donna era striata di rosso, un rosso che contribuiva a tenere alta la turgidezza della mia asta, che svettava in mezzo alle mie cosce.</p>

<p>Iniziai ad applicare i pesi sul corpo della mia futura schiava, ne avevo acquistato quattro abbastanza grossi, e avevo preso anche delle mollette apposite. Ne applicai due ai capezzoli e due alle labbra della vagina, ero sicuro che con il passare dei minuti avrebbe iniziato a soffrire, e usai quel tempo per colorare il suo corpo con la cera calda. La sentivo ansimare ma non protestava, soffriva e lo faceva in silenzio, dandomi ancora una volta la sicurezza che avevo scelto bene nell’individuarla come schiava. </p>

<p>Era il frustino che avevo riservato per ultimo e lo usai per fargli "saltare" dal corpo i pesi. Sapevo, per averlo letto, che era uno dei procedimenti più dolorosi da sopportare, e i piccoli urletti che lanciava Marta ad ogni colpo, non facevano altro che sottolineare che avevo letto il giusto. Superò anche questa prova senza protestare. </p>

<p>Eravamo arrivati quasi alla fine, levai la benda dal viso di Marta, e non senza soddisfazione vidi che i suoi occhi erano lucidi ma appagati, stava superando la prova e lo stava facendo a pieni voti. La feci mettere in ginocchio e sfruttando lo stipite della porta gli legai le mani, in maniera tale che esse rimanessero in alto, mi spogliai e avvicinai il mio cazzo alla sua bocca, inizio ad allungare la lingua per toccarlo, non gli lo permisi, erano altri i miei intenti. Volevo l’ultima umiliazione prima di essere soddisfatto appieno, gli pisciai addosso. </p>

<p>Fu sorpresa dall'arrivo della pioggia dorata, era una cosa che non si aspettava minimamente, in maniera automatica chiuse la bocca, per poi riaprirla dopo qualche secondo, non si tiro indietro dal bere la mia orina. Fu l’atto finale, un atto che mi diede la sicurezza di aver trovato la mia schiava. </p>

<p>La slegai e la mandai a fare una doccia, al suo ritorno la scopai con dolcezza, venne immediatamente inondando il materasso di umori, era troppo eccitata per riuscire a fermarsi, un godimento sottolineato dalle sue urla e dal suo sguardo, uno sguardo di cagna in calore che non avevo mai visto prima, e che contribuiva a tenere alta la mia eccitazione. </p>

<p>Mentre la scopavo vidi la luce dell’alba, la notte era passata, avevo trovato la mia unica schiava, la feci mettere in ginocchio, e depositai sulla sua lingua la mia crema calda, come al solito non mi deluse, la ingoio senza battere ciglio.</p> 

<p>Gli dissi che se voleva poteva riposare, io sarai andato via. Feci una doccia e la guardai dormire mentre mi rivestivo, aveva uno sguardo soddisfatto che mi fece felice. La salutai con un bacio sulla fronte, "ciao bambolina" gli dissi, mi rispose nel dormiveglia "ciao…padrone".</p>


<p>Componi il numero <strong><a href="tel:0689083867" data-track-content="" data-content-name="0689083867" data-content-piece="www.raccontierotici24.it">06.890.83.867</a>&nbsp;</strong>e ascolta il messaggio gratuito, risparmi fino a 50 centesimi di euro al minuto.</p>
<p><a href="tel:0689083867"><img class="alignnone size-full wp-image-101" style="display: block; margin-left: auto; margin-right: auto;" src="//www.raccontierotici24.it/wp-content/uploads/2015/08/mature-al-telefono-con-carta-di-credito.jpg" alt="mature al telefono con carta di credito" width="687" height="271" /></a></p>