<p>Il telefono era squillato poco dopo le undici del mattino. Avevo una montagna di impegni lavorativi ma sapevo di non poter semplicemente ignorare la chiamata. Avevo deciso di essere la sua schiava in un lontano giorno di primavera dopo aver conosciuto quello splendido ragazzo in un campo da tennis insieme alla mia migliore amica.</p>
<p>Da subito mi aveva colpito per la sua sicurezza di s&egrave; e dopo le prime titubanti e timide uscite a due, eravamo diventati come quelle coppie che si conoscono da anni. Nonostante la scarsa stima che avevo nei giochi di ruolo, Marco mi aveva fatto conoscere un mondo totalmente diverso nel quale perdersi e nel quale trasformarsi in qualcun'altro.</p>
<p>Io ero una persona di una certa classe sociale e l'ambiente nel quale lavoravo tendeva a stimarmi e lodarmi continuamente.</p>
<h2 style="text-align: center;"><strong>Chiama subito: <a href="tel:899.89.82.88" data-track-content="" data-content-name="899898288" data-content-piece="www.raccontierotici24.it">899.89.82.88</a></strong></h2>
<p><img src="/storage/chicon.png" alt="svizzera" width="26" height="17" /> Per accedere alle chiamate erotiche dalla Svizzera componi il seguente numero:</p>
<ul>
<li>CHIAMATE EROTICHE: <a style="font-size: 15px;" href="tel:0906.906.901" data-track-content="" data-content-name="0906906901" data-content-piece="www.raccontierotici24.it"> 0906.906.901</a> A 0,99 CHF AL MINUTO</li>
</ul>
<p>Avevo sotto di me circa 250 persone e collaboravo con centinaia di amministratori delegati sparsi nel mondo. Avevo tutto il potere che sognavo da sempre, ma allora perch&eacute; con Marco mi ero piegata a giochi che sminuivano la mia personalit&agrave;? Forse per staccare la spina. Forse per interpretare ruoli di sottomissione ai quali non ero assolutamente abituata. Non sapevo come o il perch&eacute;, ma lentamente avevo concordato con lui e avevo accettato la sua proposta cos&igrave; bizzarra.</p>
<p>Ero diventata la sua schiava. Non significava banalmente servirlo e riverirlo ogni giorno e in ogni momento. No. Essere la schiava di qualcuno andava oltre al mero essere a disposizione di una persona. Voleva dire assecondare le sue fantasie facendole tue. Subire un trattamento a tratti forte e schiacciante, ma che da un certo punto di vista andava a sollecitare emozioni ed eccitazioni mai provate prima.</p>
<p>'Pronto?' - risposi con trepidante attesa ma anche con un sussurro pronunciato sottovoce. Ero nel pieno di una riunione. Non avrei potuto rispondere ma i patti erano chiari. Lui era il mio padrone e io non dovevo mai disobbedire alle sue richieste. Guardai gli occhi dei massimi dirigenti che attendevano fissandomi con una certa aria di fastidio per l'interruzione improvvisa.</p>
<p>''Posso richiamarla dopo?'' - provai a chiedere con timore. Un conto era un gioco, un conto era il lavoro.</p>
<p>''Non ci pensare nemmeno. Adesso vai in bagno e ti levi gli slip. Poi torna pure a lavoro e aspetta mie istruzioni' - e senza aggiungere altro, la telefonata si concluse bruscamente. Avrei potuto mentire in seguito dicendo che avevo eseguito l'ordine, d'altra parte Marco abitava e lavorava in un paese a circa 200 chilometri di distanza e i nostri incontri avvenivano circa una volta al mese per qualche breve fuga programmata in anticipo.</p>
<p>Eppure, come sempre, quando mi butto anima e corpo in un progetto, io non vengo mai meno ai miei impegni. Mi scusai con il resto dei colleghi e avvisai che mi dovevo dirigere in ufficio per una chiamata dal Giappone che data la prossimit&agrave; della chiusura della borsa nipponica, non avrei potuto evitare.</p>
<p>Chiamai 5 minuti di pausa e corsi via. Una volta chiusa nello sportello del bagno, mi sentii sopraffatta da un miscuglio di emozioni. Mentre levavo le mutandine, una strana eccitazione mi colp&igrave; lo stomaco e riemp&igrave; il mio corpo di brividi di piacere. Stavo quasi per rientrare nella sala dei meeting, quando arriv&ograve; un sms sul cellulare.</p>
<p>'Ora che sei libera da stoffa inutile, infila una penna in quella preziosa patatina e tienila l&igrave; tutto il giorno.'</p>
<p>Rimasi a bocca aperta. Davvero voleva che facessi questo? Come sempre, non mi soffermai sulla stranezza della richiesta e come un automa, mi incamminai verso il mio spazioso ufficio con vista sulla baia. Mi sedetti alla scrivania cercando di osservare se dallo stretto inserto in vetro nella pesante porta legnosa, si potesse vedere cosa succedeva dentro. No. Nessuno poteva vedermi. Allargai piano piano le cosce sentendomi un pochino umiliata.</p>
<p>Aveva fatto centro anche quella volta. Sminuirmi, usarmi e umiliarmi era lo scopo di quel morboso ed eccitante gioco. Scelsi una piccola ma tozza penna a stilo che portava incise le mie iniziali. Sorrisi per la surreale situazione e dopo averla umettata con la bocca, aprii le mie succose e depilate labbra per inserire l'oggetto peccaminoso. Non potevo crederci. Ora sarei rientrata in riunione con una penna dentro di me e senza mutandine.</p>
<p>La giornata stava proseguendo tutto sommato senza particolari intoppi, se non che spesso mi trovavo a muovermi animatamente sulla sedia per non sentire troppo quell'ingombrante e succulento ospite che occupava i miei spazi pi&ugrave; intimi. Notai sullo schermo del computer acceso che mi era stato notificato l'arrivo di una mail.</p>
<p>Il direttore di filiale aveva preso il mio posto dopo la mia conclusione e stava ora discutendo di un nuovo contratto quando mi accorsi che era ancora Marco.</p>
<p>Strabuzzai gli occhi e soffocai un grido di stupore quando scorsi con gli occhi il testo che avevo ricevuto.</p>
<p>'Tu sei la mia schiava e io voglio vederti domani. Non m'importa se hai impegni, se hai tempo libero o no. Tu domani prendi la macchina e mi raggiungi all'Hotel Delle Rose. Lascerai la penna dentro il tuo corpo fino ad allora e solo quando decider&ograve; il momento giusto, potrai estrarla. Andremo a cena nel ristorante pi&ugrave; elegante e tu ad un certo punto dovrai abbaiare ed inginocchiarti ai miei piedi per domandarmi del cibo. Se farai abbastanza guaiti da attirare l'attenzione intorno a noi, io sar&ograve; clemente e ti conceder&ograve; di assaggiare qualcosa.</p>
<p>Poi, una volta terminata la mia cena, sceglier&ograve; un uomo qualunque che dovrai sedurre e portarlo in camera con noi. A quel punto, sarai la schiava di entrambi e ti faremo cose indicibili per tutta la notte, finch&eacute; stanchi ed appagati, riverseremo su di te tutti i succhi del nostro sesso. Ora vai in macchina, so che ti sei eccitata al solo pensiero. Vai nel parcheggio, apri le tue belle gambe e masturbati fino a godere. So che lo vuoi e anche se non voglio premiarti troppo, ti concedo un orgasmo cos&igrave; domani sarai pronta per farti fare tutto quello che voglio.'</p>
<p>Vuoi spendere di meno?</p>
<p>Componi il numero <strong><a href="tel:0689083867" data-track-content="" data-content-name="0689083867" data-content-piece="www.raccontierotici24.it">06.890.83.867</a>&nbsp;</strong>e ascolta il messaggio gratuito, risparmi fino a 50 centesimi di euro al minuto.</p>
<p><a href="tel:0689083867"><img class="alignnone size-full wp-image-101" style="display: block; margin-left: auto; margin-right: auto;" src="//www.raccontierotici24.it/wp-content/uploads/2015/08/mature-al-telefono-con-carta-di-credito.jpg" alt="mature al telefono con carta di credito" width="687" height="271" /></a></p>
<p>Dieci minuti dopo, con una banale scusa, ero gi&agrave; nella mia vettura a toccarmi. Gridai forse pi&ugrave; forte del solito, fortunatamente a quell'ora il sotterraneo era deserto. Solo io, la mia mano che si muoveva rapidamente sotto la gonna e i miei sensi che esplodevano in un piacere incontenibile.</p>