<p>Se non fosse stato per il ritardo di quel treno, oggi forse, racconterei una storia diversa. Il mio arrivo a Genova, era previsto per il primo pomeriggio, ma i soliti treni italiani, avevano fatto slittare l'orario ben oltre a quello preventivato. Chiamai casa per avvisare e rimasi perplessa quando nessuno rispose al telefono. Ma come era possibile?</p>
<p>Mi squill&ograve; il cellulare qualche minuto dopo e tirai un sospiro di sollievo. Sarei arrivata praticamente di notte e l'idea di rimanere nella stazione genovese ad aspettare un passaggio da sola, non era del tutto rassicurante.</p>
<h2 style="text-align: center;"><strong>Chiama subito: <a href="tel:899.89.82.88" data-track-content="" data-content-name="899898288" data-content-piece="www.raccontierotici24.it">899.89.82.88</a></strong></h2>
<p><img src="/storage/chicon.png" alt="svizzera" width="26" height="17" /> Per accedere alle chiamate erotiche dalla Svizzera componi i seguenti numeri:</p>
<ul>
<li>CHIAMATE EROTICHE ETERO: <a style="font-size: 15px;" href="tel:0906.906.901" data-track-content="" data-content-name="0906906901" data-content-piece="www.raccontierotici24.it"> 0906.906.901</a> A 0,99 CHF AL MINUTO</li>
<li>CHIAMATE EROTICHE MATURE: <a style="font-size: 15px;" href="tel:0906.906.666" data-track-content="" data-content-name="0906906666" data-content-piece="www.raccontierotici24.it">0906.906.666</a> A 0,99 CHF AL MINUTO</li>
<li>CHIAMATE EROTICHE TRANS: <a style="font-size: 15px;" href="tel:0906.869.869" data-track-content="" data-content-name="0906869869" data-content-piece="www.raccontierotici24.it"> 0906.869.869</a> A 0,99 CHF AL MINUTO</li>
</ul>
<p>Mi accordai con mio fratello, che oltretutto, mi inform&ograve; di una partenza improvvisa della nostra famiglia. Un compleanno fuori programma, dovuto ad un invito dell'ultimo secondo, aveva fatto partire tutti. Mi chiese se avevo preferenze per la cena, ma come al solito, non ascolt&ograve; le mie risposte.</p>
<p>Avevo chiesto di mangiare una pizza, ma quando arrivammo a casa, notai che aveva preso del carpaccio. E io, vegetariana da sempre, lo guardai con un punto di domanda negli occhi.</p>
<p>'Scusa Sarah, non mi ricordavo, davvero. Ho molto per la testa in questi giorni e tra l'altro &egrave; da una vita che non ci vediamo, davvero, mi &egrave; sfuggito di mente. Vado a prenderti una pizza qui all'angolo, sono aperti fino a tardi.'</p>
<p>Vuoi spendere di meno?</p>
<p>Componi il numero <strong><a href="tel:0689083867" data-track-content="" data-content-name="0689083867" data-content-piece="www.raccontierotici24.it">06.890.83.867</a>&nbsp;</strong>e ascolta il messaggio gratuito, risparmi fino a 80 centesimi al minuto.</p>
<p><a href="tel:0689083867"><img class="alignnone size-full wp-image-101" style="display: block; margin-left: auto; margin-right: auto;" src="//www.raccontierotici24.it/wp-content/uploads/2015/08/mature-al-telefono-con-carta-di-credito.jpg" alt="mature al telefono con carta di credito" width="687" height="271" /></a></p>
<p>Decisi che nel frattempo mi sarei fatta una doccia. Aveva ragione. Non vedevo la mia famiglia da tanto, troppo tempo. Ero scappata dall'Italia quasi subito dopo il diploma e ormai avevo una vita tutta mia in Irlanda. Non sarei pi&ugrave; tornata a vivere nel mio paese d'origine e la mia famiglia, restia da sempre a viaggiare all'estero, mi era venuta a trovare solo una volta in ben 13 anni. Per quanto riguarda me, erano ormai 6 anni che non mettevo piede su suolo italico.</p>
<p>Mio fratello, il mio cucciolo pi&ugrave; grande di me di un anno, era ormai diventato un uomo e io facevo fatica a riconoscerlo. Stargli accanto, mi dava la fastidiosa sensazione, di essere vicino ad uno sconosciuto. Mi stavo crogiolando sotto il getto dell'acqua calda, quando sentii la porta del bagno aprirsi.</p>
<p>'Sarah, sono tornato, vieni o la pizza si raffredda' - mi disse senza entrare.</p>
<p>Mi avvolsi un asciugamano e corsi in cucina per placare in fretta la fame furiosa che avevo ormai da qualche ora. Non appena entrai, vidi mio fratello fissarmi con aria imbarazzata. 'Che c'&egrave;? Luca? Tutto ok?' - chiesi apprensiva. 'S&igrave;, s&igrave; tranquilla. E' solo... Nulla, sono solo stanco'.</p>
<p>La risposta non mi convinse, ma lasciai perdere. Dopo cena, ci ritrovammo a bere qualche bicchiere della riserva nascosta di nostro padre. Teneva sempre un qualche prezioso liquore nello sportello bar in salotto. L'aria di casa, il calore provocato dal Brandy d'annata, la stanchezza che si stava sciogliendo e la tensione di quel viaggio infinito che finalmente mi abbandonava e come in un sogno, mi resi conto che stavo quasi flirtando con mio fratello.</p>
<p>Ma era possibile?</p>
<p>'Cosa c'&egrave; che non va Luca, ti vedo davvero strano, con me puoi parlare' - dissi poco convinta. Come poteva parlare con una sorella che conosceva appena. Eravamo stati cos&igrave; distanti che praticamente eravamo degli estranei. Non ricordavo l'ultima volta di me e lui seduti a parlare. Lui, poi, era un detrattore accanito dei Social Network, quindi, anche da quel punto di vista, eravamo perfetti sconosciuti.</p>
<p>'Vederti con quell'asciugamano, prima, mi ha per un attimo fatto provare attrazione. Se non fossi stata mia sorella, ti avrei preso con tutta la passione che ho in corpo.'</p>
<p>La sua risposta schietta e sincera mi lasci&ograve; di sasso. Ci misi qualche minuto prima di proferire verbo. Poi, con calma, deglutii e lo guardai negli occhi.</p>
<p>'Sai, non so se &egrave; peggio il fatto di non rimanere scandalizzata o... il fatto di aver provato eccitazione durante tutta la cena. Mio Dio, stavo flirtando con te! Non mi dire che non te ne sei accorto, ho fatto la civettina per tutta la sera!' e cos&igrave; ammettendo, mi coprii la faccia con le mani e risi piano piano. Luca era mio fratello. S&igrave;, &egrave; vero, non ci vedevamo da anni, non sapevamo nulla di noi. Ma era comunque parte del mio sangue.</p>
<p>'Se fossi un uomo che entra in un bar e ci prova con te, tu che faresti?' - mi chiese avvicinandosi piano piano. Il mio corpo fremeva. L'unica cosa razionale a cui riuscivo a pensare, era quella di farmi prendere dalle sue braccia muscolose e lasciarmi andare sotto di lui.</p>
<p>'Sbagliamo e lo sai. Ci pentiremo e lo sai. E' la cosa pi&ugrave; ignobile che potremmo fare e tu questo lo sai. Ma perch&eacute; non posso fare a meno di immaginare il tuo corpo nudo che si prende ogni centimetro del mio?' - dissi quasi sottovoce. Luca non si fece pregare. All'inizio fu un pochino imbarazzante. Ma la voglia e l'eccitazione di assaporarci, fu talmente esponenziale, da farci dimenticare chi fossimo e cosa rappresentassimo l'una per l'altro.</p>
<p>'Ti piace sorellina?' - mi disse spingendosi dentro di me, con una forza ed un sensuale travolgimento da lasciarmi quasi svenire dal piacere. 'Dai fratellino, puoi fare di pi&ugrave;' - lo incoraggiai iniziando un percorso di battute spinte sulla nostra parentela, che sarebbero potute sembrare inopportune, ma che in quel momento, parevano perfette per aumentare un'intesa cos&igrave; perfetta che mai avevo provato prima. Ci sapeva fare. D'altronte, buon sangue non mente.</p>
<p>Mi fece godere come nessuno mai. Mi disse che per lui fu un'esperienza magica, quasi mistica. Nessun orgasmo era stato mai cos&igrave; intenso. Mai un incontro di sesso, lo aveva travolto e coinvolto come in questa fugace notte con me. Ci guardammo a lungo, dopo. Non seppi dire nemmeno io quali erano i sentimenti contrastanti che ci passavano per la mente. Solo di una cosa ero sicura. Lo avrei voluto riprovare subito, poi ancora e ancora. Era nato qualcosa? Non lo sapevo, ma il mio rientro in Irlanda, di colpo, sembr&ograve; molto, molto lontano.'</p>