<p>La mia non &egrave; una passione sessuale ma uno "stile di vita", sono una schiava e lo sono sempre stata. Figlia di due genitori separati da bambina ero un "pacco" per cui combattere, da adolescente la "sfigata" del gruppo, da giovane donna quella che "tutti si sbattevano".</p>
<h2 style="text-align: center;"><strong>Chiama subito: <a href="tel:899.89.82.88" data-track-content="" data-content-name="899898288" data-content-piece="www.raccontierotici24.it">899.89.82.88</a></strong></h2>
<p><img src="/storage/chicon.png" alt="svizzera" width="26" height="17" /> Per accedere alle chiamate erotiche dalla Svizzera componi il seguente numero:</p>
<ul>
<li>CHIAMATE EROTICHE: <a style="font-size: 15px;" href="tel:0906.906.901" data-track-content="" data-content-name="0906906901" data-content-piece="www.raccontierotici24.it"> 0906.906.901</a> A 0,99 CHF AL MINUTO</li>
</ul>
<p>Il sesso mi &egrave; sempre piaciuto, ma dopo un po&rsquo; non trovavo piacere, gli uomini o erano troppo romantici o puntavano solamente alla mia figa. Fin quando non &egrave; arrivato lui, Sandro. Pi&ugrave; grande di me mi trattava con sufficienza, non sembrava essere interessato al mio corpo, ma sembrava conoscermi da sempre, mi guardava con i suoi occhi verdi e mi faceva "vibrare dentro" senza neppure toccarmi. Non chiedeva mai "per favore" ma pretendeva.</p>
<p>Era il periodo che lavoravo in un ristorante e lui veniva ogni sera, sedeva sempre allo stesso tavolo ed io correvo per arrivare "a servirlo" per prima. Ambivo ad avere uno sguardo da lui, ma lui non mi calcolava minimamente.</p>
<p>Una sera improvvisamente mi disse "vieni in bagno devo dirti una cosa". Fui tentata di rifiutare ma ero troppo presa da lui, e cosi dissi alla mia collega di sostituirmi e superai la porta della toilette. Fu la migliore decisione della mia vita. Non lo vidi subito ma lo sentii immediatamente, era dentro il bagno degli uomini e ascoltai la sua voce roca "Marta vieni qui". Solo sentirlo mi fece venire la pelle d&rsquo;oca.</p>
<p>Che cosa voleva? Come sapeva che ero io? Perch&eacute; si nascondeva? Mi feci coraggio ed entrai.</p>
<p><strong>Vuoi spendere di meno?</strong></p>
<p>Componi il numero <strong><a href="tel:0689083867" data-track-content="" data-content-name="0689083867" data-content-piece="www.raccontierotici24.it">06.890.83.867</a>&nbsp;</strong>e ascolta il messaggio gratuito, risparmi fino a 50 centesimi di euro al minuto.</p>
<p><a href="tel:0689083867"><img class="alignnone size-full wp-image-101" style="display: block; margin-left: auto; margin-right: auto;" src="//www.raccontierotici24.it/wp-content/uploads/2015/08/mature-al-telefono-con-carta-di-credito.jpg" alt="mature al telefono con carta di credito" width="687" height="271" /></a></p>
<p>Era in piedi sulla tazza, il suo cazzo fuori dai pantaloni che mi puntava in maniera sfacciata, lui che mi sorrideva. "Entra troia e chiudi la porta e poi... succhia", non disse altro, ma mi guardava con un'intensit&agrave; che non mi diede la forza di rifiutare. Feci come disse, mi ricordo che avevo il cazzo esattamente davanti alla bocca e non dovetti sforzarmi per imboccarlo. Lui non si mosse minimamente, si limitava a guardarmi ma sentivo i suoi occhi che "mi trafiggevano" la nuca. Lavorai di bocca per qualche minuto poi lo senti dire "fermati cagna e torna a lavorare, ci sar&agrave; tempo per farmi godere". La sua frase mi disorient&ograve;, ero sicura che voleva "godere" dentro la mia bocca, ma non erano questi i suoi piani.</p>
<p>Mi sentivo attratta da lui e feci finta di non sentirlo, la mia bocca non voleva lasciare libera la sua splendida asta. Lui non si scompose, ma con una velocit&agrave; impressionante mise la mano dentro la mia abbondante scollatura e al primo colpo trovo il capezzolo, inizi&ograve; a stringerlo tra le dita, prima piano e poi pi&ugrave; forte fino a quando non senti un dolore irraggiarsi per tutto il corpo, mi staccai da lui per gridare ma il suo sguardo mi blocc&ograve;. Si abbass&ograve; e piano nell&rsquo;orecchio mi disse "puttanella sono io che ti dico quando devi continuare, e adesso non &egrave; il momento" sottoline&ograve; le parole continuando a stringere il capezzolo.</p>
<p>Volevo urlare ma sapevo che avrei rovinato tutto, mi allontanai e mentre lo facevo le sue dita, iniziarono a mollare la presa. Non proferimmo pi&ugrave; parola e come aveva detto Sandro, tornai in sala. Lui apparve qualche minuto dopo, si accomod&ograve; al suo tavolo come se nulla fosse accaduto e continu&ograve; a cenare. Non mi degn&ograve; pi&ugrave; di uno sguardo. Alla fine della cena chiese il conto e mi diete la carta di credito. Insieme c&rsquo;era un biglietto che io feci scivolare furtivamente nella tasca del grembiule, pag&ograve; e usc&igrave;. Morivo dalla voglia di sapere cosa c&rsquo;era scritto e fugacemente diedi uno sguardo, il biglietto riportava con una grafia elegante un indirizzo e un messaggio che diceva "se decidi di venire diventerai la mia schiava&hellip;ti aspetto".</p>
<p>Queste poche parole mi fecero andare in confusione, non mi conosceva neppure e mi proponeva non di diventare la sua donna o la sua amante, ma ancor peggio la "sua schiava". Che cosa intendeva con questo termine? Dovevo accettare l&rsquo;invito? Ci pensai per tutta la sera. Il mio cuore mi diceva di rifiutare, l&rsquo;umido tra le mie cosce m&rsquo;imponeva di accettare. Accettai. Arrivai a casa sua con uno stato d&rsquo;animo che andava dalla paura dell&rsquo;ignoto, all&rsquo;eccitazione per un qualcosa che avevo sempre ambito di fare: diventare una schiava.</p>
<p>Sandro mi apr&igrave;, si era cambiato e vestiva adesso elegantemente, mi fece accomodare e senza proferire parola mi bacio. Fu un bacio intenso, sentivo la sua lingua nella mia bocca. Si stacc&ograve; dopo qualche minuto e un sottile filo di saliva rimase tra noi. "vai di l&agrave; e spogliati Marta", mi sorprese con la sua dolcezza, e per un attimo mi illusi che voleva "una donna" e non "una schiava". La mia illusione dur&ograve; poco, la stanza che mi aveva indicato conteneva tutta una serie di strumenti che non lasciavano dubbi su quale sarebbe stata la natura del nostro rapporto. Le pareti erano piene di vibratori, mollette per i capezzoli, fruste, bavagli. Al centro della stanza campeggiava una "croce di Sant&rsquo;Andrea", sulla quale erano applicate delle cinghie che servivano per bloccare gli arti.</p>
<p>L&rsquo;illuminazione era demandata ad alcuni candelabri, tutto in quella stanza faceva pensare a una sala di tortura. Ebbi il tempo di spogliarmi e lui entr&ograve;, questa volta era a petto nudo e con un pantalone di pelle su cui "spiccava" il suo cazzo. Fu una notte splendida, Sandro mi leg&ograve; e mi bend&ograve; poi inizio con maestria a "fare vibrare il mio corpo", torturo i miei capezzoli con durezza, sembrava affascinato dal mio seno, lo strizzava con un&rsquo;intensit&agrave; mai provata, e mentre lo faceva, sentivo la mia figa in fiamme. Lui lo sapeva e soprattutto sapeva quando fermarsi, ogni tanto, interrompeva i movimenti e mi sussurrava parole dolci, dava al mio corpo la possibilit&agrave; di calmare l&rsquo;eccitazione, e quando questo avveniva&hellip;iniziava nuovamente a torturarlo.</p>
<p>Mi penetr&ograve; con pi&ugrave; tipi di vibratori, mi frust&ograve; con durezza ma non sentivo dolore sentivo solo il piacere di farlo felice, e soprattutto sentivo la mia carne ribollire dal desiderio. Non so quando dur&ograve;, quella "prima sessione", so solo che alla fine mi sleg&ograve;.</p>
<p>Io ero sempre bendata, e lui mi guid&ograve; in un'altra stanza, l&igrave; mi appoggio delicatamente su un letto, e inizio a penetrarmi con dolcezza. Mentre lo faceva, mi tolse la benda, e guardandomi negli occhi mi disse "sei stata brava troia, godi adesso". Venni come non avevo mai fatto prima, il mio corpo vibrava e il piacere mi squassava le carni, fu magnifico. Quella notte ho dormito da lui e da allora non sono solo la sua schiava, ma anche la sua donna, e sono&hellip; orgogliosa di esserlo.</p>