<p>Era la prima volta per me. Un gentile maestro di paese che ha sempre avuto per&ograve; la fantasia erotica di farsi scopare da un transessuale. Non ho mai capito cosa si celi dietro questa torbida fantasia, ma mi sono spesso ritrovato a masturbarmi davanti ai porno con a tema delle sensualissime transessuali.</p>
<p>Se non fosse per la mia reputazione a rischio, forse sarei andato prima a cercare di soddisfare questa mia passione sfrenata. Ma, vuoi la paura di farmi beccare dalle pattuglie, vuoi il timore di essere colto da qualcuno che mi conosce, alla fine mi sono sempre dovuto accontentare dei filmini su internet.</p>
<p>Neanche 45 anni ed ancora single per scelta, non avevo altro motivo per sentirmi in colpa. Era una cosa che volevo fare da tempo, non ferivo nessuno e se anche la legge me lo vietava, io ero del tutto intenzionato a trovare la cavalla che mi avrebbe cavalcato come si deve. Non sono omosessuale, mi piace il cazzo, ma ad indossarlo con maestria deve essere un'affascinante donna. So perfettamente che le donne di cui mi invaghisco sono degli uomini, ma la loro capacit&agrave; di essere femminili e sexy supera di molto quella di tante mie coetanee completamente donne dalla nascita.</p>
<h2 style="text-align: center;"><strong>Chiama subito: <a href="tel:899.89.82.88" data-track-content="" data-content-name="899898288" data-content-piece="www.raccontierotici24.it">899.89.82.88</a></strong></h2>
<p><img src="/storage/chicon.png" alt="svizzera" width="26" height="17" /> Per accedere alle chiamate erotiche dalla Svizzera componi i seguenti numeri con TARIFFA A 0,99 CHF AL MINUTO.</p>
<ul>
<li>CHIAMATE EROTICHE ETERO: <a style="font-size: 15px;" href="tel:0906.906.901" data-track-content="" data-content-name="0906906901" data-content-piece="www.raccontierotici24.it"> 0906.906.901</a> A 0,99 CHF AL MINUTO</li>
<li>CHIAMATE EROTICHE MATURE: <a style="font-size: 15px;" href="tel:0906.906.666" data-track-content="" data-content-name="0906906666" data-content-piece="www.raccontierotici24.it">0906.906.666</a> A 0,99 CHF AL MINUTO</li>
<li>CHIAMATE EROTICHE TRANS: <a style="font-size: 15px;" href="tel:0906.869.869" data-track-content="" data-content-name="0906869869" data-content-piece="www.raccontierotici24.it"> 0906.869.869</a> A 0,99 CHF AL MINUTO</li>
</ul>
<p>Cos&igrave; era arrivato il giorno. Avevo saputo che nella via grande, quella che dal paese ti porta verso la vecchia stazione, di notte si potevano trovare prostitute e trans per pochi spiccioli. Ma era la mia prima volta e avevo immaginato tutto con cos&igrave; tanta dovizia di particolari succosi, che non potevo rischiare di mandare all'aria tutto a causa della fretta, della paura e dell'insicurezza di chiss&agrave; cosa.</p>
<p>Avevo sfogliato i giornali alla ricerca di qualche annuncio ed avevo trovato un succulento invito di una tale Patrizia, che descrizione alla mano, sembrava proprio il tipo che preferivo io: mora focosa sudamericana, alta e con una quinta di seno da far svenire chiunque.</p>
<p>Secondo il suo annuncio infuocato, aveva anche in dotazione da madre natura un bel cazzo nodoso e grosso. Non restava che recensirla dal vivo. Provai a chiamarla la settimana prima per chiedere qualche informazione. Non ero avvezzo ad incontri del genere, avevo davvero un po' di timore di risultare inesperto e facilmente prevedibile, ma non avevo molte altre alternative. In casa era davvero impossibile parlarne ed in paese, sebbene voci di corridoio svelassero qualche pettegolezzo piccante, era impensabile domandare esperienze dirette.</p>
<p>Cos&igrave; una volta composto il numero di telefono, deglutii ed attesi in linea. Una voce calda e solo lontanamente maschile rispose e mi mise subito a mio agio.</p>
<p>Mi spieg&ograve; la strada per arrivare, casa sua non distava pi&ugrave; di una ventina di chilometri dal mio domicilio, mi disse la tariffa e ci mettemmo d'accordo per il gioved&igrave; notte. L'appuntamento era fissato intorno alle dieci di sera, ma mi premunii di prenotare almeno due ore perch&eacute;, come le spiegai, odio la fretta e mi piace viziare le mie fantasie. Soprattutto ora che sarebbero presto diventate la realt&agrave; che tanto desideravo.</p>
<p>Arrivai con largo anticipo e stetti un po' in macchina per non far subito notare la tempestiva voglia con il quale ero giunto. Quando fu quasi l'ora stabilita, decisi che era anche arrivato il momento di citofonare.</p>
<p>Casa sua era in un condominio fuori mano, all'ultimo piano e protetto da un sistema di sorveglianza sofisticato.</p>
<p>Ad aprirmi la porta, fu subito la mia dea. Patrizia indossava una vestaglia completamente trasparente, tacchi vertiginosi ed un trucco forte ma non eccessivo. La sue braccia mi strinsero e la sua bocca schiocc&ograve; un bacio succoso sulle mie labbra. La cosa mi lasci&ograve; di stucco.</p>
<p>'Di solito in questo mestiere non bacia nessuno, ma io amo i miei clienti e voglio coccolarli e viziarli e so che a volte giocare alla fidanzatina piace molto' - disse Patrizia prendendomi per mano.</p>
<p>Andammo in una camera dalle luci rosa e rosse, soffuse, e mi mostr&ograve; un letto rotondo sul quale mi fece accomodare. Indic&ograve; gli specchi posizionati tutti intorno a creare un perimetro sul quale riflettersi.</p>
<p>'Vedi questi specchi? Non ti perderai neanche un secondo di quanto faremo, avrai una visuale a 360 gradi e cos&igrave; il tuo godimento sar&agrave; amplificato come mai prima, fidati della tua Patty' - mi disse alzandosi.</p>
<p>'Spogliati lentamente, cos&igrave; io ti osservo e poi inizio io a farti intravedere il mio corpo' - stuzzic&ograve; la mia eccitazione con un occhiolino, alzandosi su quelle lunghe gambe e lasciando cadere la vestaglia. Rimase in perizoma e con le tette completamente libere e nude.</p>
<p>Iniziai a toccarmi e a masturbarmi, perch&eacute; alla vista di quello splendore tutto mio per un paio di ore, il mio cazzo stava davvero esplodendo. Patrizia se ne accorse e, senza dire una parola, si sedette sul letto ed inizi&ograve; a giocare con il mio buchino segreto. Sentii la sua lingua invadermi nel profondo e poi, con un gesto che ricorder&ograve; per molto tempo, infil&ograve; un dito nel mio culo.</p>
<p>'Ti fa male, maialino? Vuoi che ci metta qualcosa di pi&ugrave; grosso?' - mi disse facendomi vedere attraverso lo specchio il suo uccello enorme libero e pronto a strapazzarmi.</p>
<p>'Oh mio dio, s&igrave; ti prego, sfondami e fammi sentire cosa si prova...' - la supplicai con voce eccitata.</p>
<p>Mi prese le natiche con fare esperto, le allarg&ograve; per bene e con fare molto da film porno, ci sput&ograve; intorno, per lubrificare per bene. Una volta ammorbidita la zona, finalmente, mi penetr&ograve;.</p>
<p>&Egrave; stato surreale. Sentivo un cazzo enorme sfondarmi con colpi secchi ma potevo toccare nello stesso momento delle tette cos&igrave; abbondanti da non starmi nemmeno in bocca.</p>
<p>Grazie agli specchi mi godetti interamente la scena erotica che stava accadendo proprio a me. Le due ore con Patrizia furono solo l'inizio della mia attivit&agrave; extra scolastica notturna, perch&eacute; una volta provato un trans, difficilmente si pu&ograve; anche solo pensare di tornare indietro.</p>
<p><strong>Vuoi chiamare, godere e spendere di meno?</strong></p>
<p>Componi il numero <strong><a href="tel:0689083867" data-track-content="" data-content-name="0689083867" data-content-piece="www.raccontierotici24.it">06.890.83.867</a>&nbsp;</strong>e ascolta il messaggio gratuito, risparmi fino a 50 centesimi al minuto.</p>
<p><a href="tel:0689083867"><img class="alignnone size-full wp-image-101" style="display: block; margin-left: auto; margin-right: auto;" src="//www.raccontierotici24.it/wp-content/uploads/2015/08/mature-al-telefono-con-carta-di-credito.jpg" alt="mature al telefono con carta di credito" width="687" height="271" /></a></p>