<p>Quando mi ha fermato la pattuglia, non avrei mai immaginato che la serata potesse prendere una piega cos&igrave; surreale ed inaspettata.</p>
<p>Io e la mia amica avevamo bevuto parecchio, sapevo che guidando sarei sicuramente stata a rischio di ritiro di patente, ma quando i fumi dell'alcool urlano pi&ugrave; alti della coscienza, non pu&ograve; che finire anche peggio di quanto si era immaginato.</p>
<p class="uk-text-center"><img src="/storage/chicon.png" alt="svizzera" width="26" height="17" /> Per accedere alle chiamate erotiche dalla Svizzera componi i seguenti numeri:</p>
<div class="uk-grid-divider uk-child-width-expand@s" uk-grid><div><p class="uk-text-center">CHIAMATE EROTICHE ETERO: <a style="font-size: 15px;" href="tel:0906.906.901" data-track-content="" data-content-name="0906906901" data-content-piece="www.raccontierotici24.it"> 0906.906.901</a> A 0,99 CHF AL MINUTO</p></div>
<div><p class="uk-text-center">CHIAMATE EROTICHE MATURE: <a style="font-size: 15px;" href="tel:0906.906.666" data-track-content="" data-content-name="0906906666" data-content-piece="www.raccontierotici24.it">0906.906.666</a> A 0,99 CHF AL MINUTO</p></div>
<div><p class="uk-text-center">CHIAMATE EROTICHE TRANS: <a style="font-size: 15px;" href="tel:0906.869.869" data-track-content="" data-content-name="0906869869" data-content-piece="www.raccontierotici24.it"> 0906.869.869</a> A 0,99 CHF AL MINUTO</p></div></div>
<hr>
<p>O meglio, non direi proprio peggio. Direi inaspettatamente diverso e totalmente differente dalla serata che avevo pensato. Una volta uscite dalla discoteca, la mia amica aveva preso la via di casa con un conoscente che sperava probabilmente di concludere a letto la nottata. Mentre io, che non mi fido di chi conosco appena, avevo mandato all'aria un possibile approccio da parte di un ragazzo.</p>
<p>In realt&agrave; non sono mai stata troppo santarellina, ma quella sera, nonostante una discreta voglia che sentivo crescere sempre di pi&ugrave; da quando il mio ultimo ragazzo mi aveva lasciato, volevo solo andare a casa a rilassarmi.</p>
<p>La musica in discoteca era stata troppo martellante, e complice una leggera noia, non mi ero particolarmente divertita anche se l'alcool aveva comunque portato dei benefici.</p>
<h2 style="text-align: center;"><strong>Chiama subito una moglie vogliosa: <a href="tel:899.89.82.88" data-track-content="" data-content-name="899898288" data-content-piece="www.raccontierotici24.it">899.89.82.88</a></strong></h2>
<div class="uk-grid-divider uk-child-width-expand@s" uk-grid><div><img class="uk-align-center uk-margin-small-bottom" src="/storage/italy.png" alt="svizzera" width="26" height="17" /><p class="uk-text-center">CHIAMATE EROTICHE MATURE: <a style="font-size: 15px;" href="tel:899.37.00.32" data-track-content="" data-content-name="899370032" data-content-piece="www.raccontierotici24.it">899.37.00.32</a></p></div>
<div><img class="uk-align-center uk-margin-small-bottom" src="/storage/chicon.png" alt="svizzera" width="26" height="17" /><p class="uk-text-center">CHIAMATE EROTICHE MATURE: <a style="font-size: 15px;" href="tel:0906.906.666" data-track-content="" data-content-name="0906906666" data-content-piece="www.raccontierotici24.it">0906.906.666</a> A 0,99 CHF AL MINUTO</p></div></div>
<p>Tutto ci&ograve; che desideravo, era andare diretta nella mia camera, accendere il computer per lenire la mia voglia e la mia eccitazione, trastullandomi qualche minuto con il vibratore e poi uno spuntino ed un film per addormentarmi.</p>
<p>La perfetta serata della perfetta donna single.</p>
<p>Invece il destino aveva in mente qualcosa di pi&ugrave; provocante e particolarmente stravagante per me. Quando arrivai quasi all'imbocco della superstrada, vidi dei lampeggianti in lontananza.</p>
<p>'Merda'- pensai.</p>
<p>'Se inverto ora, se ne accorgono subito, cazzo' - dissi disperata. Sicuramente non avevo fortuna e sicuramente mi avrebbero fermato. Non feci neanche tempo a pensare ad una scusa plausibile per la sbornia in corso, che vidi la paletta agitarsi davanti ai miei occhi. 'Non avevo dubbi'. Non ero ubriaca e senza un alcool test, sarei sicuramente riuscita a mantenere contegno e apparenza. Invece, con questi nuovi apparecchi elettronici, era tutto molto pi&ugrave; difficile.</p>
<p>'Ha bevuto?'- mi chiese il simpatico agente dall'aria incazzata mentre tiravo gi&agrave; il finestrino. Niente buongiorno o buonasera, diretto ed antipatico come vuole il copione.</p>
<p>Spiegai all'agente che s&igrave;, mi ero fatta una birra prima di uscire dal locale e che probabilmente il mio tasso alcoolico era un pochino fuori dalla norma. Non volle sentire ragioni, nemmeno quando cercai di spiegargli che sarebbe bastato aspettare qualche manciata di minuti per avere un test pi&ugrave; veritiero.</p>
<p>'Soffi e non faccia storie' - sentenzi&ograve; il mio nuovo peggior nemico.</p>
<p>Ovviamente il test risult&ograve; positivo all'alcool ed io di colpo, sentii il terreno mancarmi da sotto i piedi.</p>
<p>Mi fu spiegato che la patente mi sarebbe stata levata per circa due mesi, che la macchina veniva sequestrata perch&eacute; non ero in grado di tornare a casa alla guida e che avrei dovuto anche pagare una multa salatissima.</p>
<p>Mi guardai attorno per vedere se c'era qualche altro sfigato come me, ma notai che eravamo solo io, l'agente che mi stava torturando ed il suo collega, spostato poco pi&ugrave; in l&agrave;, quasi annoiato e sicuramente stanco.</p>
<p>Non so come mi venne esattamente l'idea. Ma so che mi venne.</p>
<div class="uk-grid-divider uk-child-width-expand@s" uk-grid><div><p class="uk-text-center">TELEFONO EROTICO ZITTO E GODI: <a href="tel:899.84.85.97">899.84.85.97</a></p></div>
<div><p class="uk-text-center">TELEFONO EROTICO CON CARTA DI CREDITO: <a style="color: #ff0000;" href="tel:06.890.838.67">06.890.838.67</a></p></div>
<div><p class="uk-text-center">TELEFONO EROTICO BASSO COSTO: <a href="tel:899.00.33.65">899.00.33.65</a></p></div></div>
<p>Mi sentii anche un po' zoccola, in un primo momento ma poi riflettendo bene che male c'era?</p>
<p>A me piace il sesso, avrei sempre voluto provare una cosa a tre, con due uomini che mi possiedono e con il mio corpo come unico loro sfogo animalesco e, cosa pi&ugrave; importante, non avevo proprio bisogno di tutto sto iter burocratico per una bevuta in compagnia. Non volevo la multa. Volevo scopare. Ok, dovevo tentare la strada della seduzione.</p>
<p>'Senta, ma non c'&egrave; proprio modo di far finta di nulla e... che ne so, lasciarmi andare?' - dissi con un'improvvisa vocina da gatta e mentre lo guardavo, la mia mano slacci&ograve; il primo bottone della mia attillata camicetta.</p>
<p>'Pensa davvero che una scollatura la possa salvare? Se lo scordi, qui non funziona cos&igrave;. Davvero vuole uscirne indenne? Eh bella mia, altro che scollatura devi farmi vedere.' - disse toccandosi il pacco.</p>
<p>Allora era corruttibile, pensai. Adesso ci divertiamo.</p>
<p>Dissi all'agente di chiamare anche il suo collega, perch&eacute; volevo divertirmi per bene. 'Sentito la cagnetta, Luca? Cazzo finalmente qualcuna che si presta a far da troia per i nostri comodi. Di solito parlate tutte a vanvera, ma poi, al momento giusto, vi tirate indietro. Andiamo, zoccoletta, facci vedere come sai intrattenere due cazzi alla volta'.</p>
<p>Scesa dalla macchina, mi levai tutto. Rimasi nuda completamente, eccitata da morire e mi sdraiai sul cofano della mia auto con le gambe spalancate. 'Allora? Io e la mia gattina stiamo aspettando...'</p>
<p>Non se lo fecero ripetere. Uno mi tenette ben ferma ed inizi&ograve; a scoparmi mentre l'altro, che sembrava anche il pi&ugrave; eccitato dalla situazione, inizi&ograve; a farmi succhiare il suo uccello.</p>
<p>Poi di colpo sentii una risata e udii i due sussurrarsi qualcosa all'orecchio. Per un attimo ebbi perfino paura della loro fantasia malata. Invece, niente di meglio. Iniziarono a titillarmi il culo, e mentre uno si faceva spazio impalandomi completamente, l'altro continu&ograve; a scoparmi.</p>
<p>Non avrei potuto sentirmi pi&ugrave; piena. Anche se... 'La prossima volta ragazzi, chiamate il terzo, perch&eacute; al momento sono rimasta a bocca vuota, se capite cosa intendo...'- dissi mimando con la mano un pompino.</p>
<p>Loro erano increduli.</p>
<p>Mai avrebbero pensato di trovare una donna cos&igrave; tanto spregiudicata da soddisfare ogni loro fantasia.</p>
<p>Fu una serata memorabile e prima di andare via, a bordo della mia vettura e con la mia patente in tasca, mi girai verso la pattuglia che si stava rivestendo ed allungando un bacio in aria, chiesi ad alta voce il loro turno del weekend successivo!</p>
<p><strong>Vuoi chiamare, godere e spendere di meno?</strong></p>
<p>Componi il numero <strong><a href="tel:0689083867" data-track-content="" data-content-name="0689083867" data-content-piece="www.raccontierotici24.it">06.890.83.867</a>&nbsp;</strong>e ascolta il messaggio gratuito, risparmi fino a 50 centesimi di euro al minuto.</p>
<p><a href="tel:0689083867"><img class="alignnone size-full wp-image-101" style="display: block; margin-left: auto; margin-right: auto;" src="//www.raccontierotici24.it/wp-content/uploads/2015/08/mature-al-telefono-con-carta-di-credito.jpg" alt="mature al telefono con carta di credito" width="687" height="271" /></a></p>