<p>Una volta molti anni fa ero un uomo, adesso non lo sono pi&ugrave;. Il mio rapporto con il sesso &egrave; sempre stato controverso, da ragazzo complice la mia famiglia, molto religiosa, non riuscivo a capire che non mi piacevano le donne, o meglio lo capivo ma sapevo che era impossibile vivere la mia vita, all'interno del mio ambiente familiare.</p>
<p>Ho avuto qualche ragazza ma non riuscivo a soddisfarla, non mi piaceva il corpo di donna e in seguito ho capito il perch&eacute;. Sono andato via da casa a 19 anni e solo allora ho capito cosa cercavo. L&rsquo;ho capito grazie a quello che ancora &egrave; il mio compagno. Ci siamo conosciuti per sbaglio in un locale, il fato e la mancanza di posti nella sala di un ristorante sono stati i fautori della nostra storia d&rsquo;amore. La cameriera ci ha chiesto se avevamo nulla in contrario a sederci assieme e quella &egrave; stata la nostra prima cena.</p>
<p>La discussione e andata via veloce e complice una bottiglia di vino (che abbiamo acquistato in comune), il discorso &egrave; scivolato verso i nostri lati pi&ugrave; intimi. Lui non aveva problemi a raccontarmi di come fosse omosessuale, mi ha esposto senza vergogna le umiliazioni patite nel suo paesino, e di come avesse deciso di andare via da casa sua. Era come rivivere la mia storia, ma io non avevo la consapevolezza di cosa volessi, lui invece s&igrave;.</p>
<p>Finimmo la cena e dopo esserci scambiati il numero di cellulare, ritornammo nelle nostre case. Fu l&igrave; nella solitudine del mio letto che cap&igrave; che anch&rsquo;io ero nella sua stessa situazione. Non riusc&igrave; a resistere, ricordo ancora che era l&rsquo; 1.22, ma fu pi&ugrave; forte di me lo chiamai. Rispose al primo squillo e parlammo fino all&rsquo;alba. Da allora non ci siamo pi&ugrave; lasciati, sono diventato la sua puttana... con il cazzo.</p>
<p>Lui venne a casa mia subito dopo la fine della telefonata, port&ograve; due cornetti e con una dolcezza infinita m&rsquo;introdusse all&rsquo;amore omo. Avvenne tutto naturalmente senza nessun imbarazzo, m&rsquo;inizi&ograve; a baciare sul divano prima languidamente poi in maniera pi&ugrave; focosa, non aveva la fretta che avevano avuto le poche donne che avevo conosciuto. I suoi baci erano languidi ma calmi, le sue mani mi toccavano con sicurezza ma senza fretta, il suo corpo era eccitato ma tranquillo. Mi spogli&ograve; piano piano e lo prese in bocca, era il primo pompino che un uomo mi faceva, fu stupendo.</p>
<p>La sua bocca si muoveva sulla mia asta con sapienza, la sua lingua scorreva sulla mia verga lasciando scie di saliva, le sue mani torturavano il mio buchino posteriore. Nelle mie precedenti esperienze sessuali avevo avuto problemi a mantenere l&rsquo;erezione, questa volta invece il mio cazzo era duro come il marmo. Venni nella sua bocca e la cosa che mi sconvolse di pi&ugrave; fu che lui non volle essere ricambiato.</p>
<p>Con il senno di poi credo che abbia preso la decisione giusta, non voleva forzarmi ed era disposto ad aspettare. La cosa and&ograve; avanti per cinque giorni, ci vedevamo una volta al giorno e lui mi faceva godere con la sua bocca, senza volere nulla in cambio. Questo suo atteggiamento mi leg&ograve; a lui.</p>
<p>La quinta sera ero pronto al mio primo pompino. Lui non mi ferm&ograve; anzi guid&ograve; la mia testa sul suo cazzo, era steso sulla schiena, la sua verga svettava ed io dovetti reprimere un conato di vomito ma mi avvicinai e subito mi piacque. Volevo farlo felice ma ero inesperto, provai a fare come avevo visto fare e ci misi l&rsquo;impegno di una principiante, sentivo il cazzo dentro la mia bocca, lo sentivo vibrare, sentivo il suo sapore da maschio e capivo che non avrei pi&ugrave; potuto farne a meno.</p>
<p>Il giorno dopo m&rsquo;incul&ograve; per la prima volta, dolcemente mi domand&ograve; se "volevo andare fino in fondo". Io avevo un po&rsquo; di paura ma volevo donarmi a lui. Mi gir&ograve; e piano piano mi penetr&ograve;, lo sentivo tutto dentro di me, avvertivo un leggero dolore ma nulla d&rsquo;insopportabile.</p>
<p>Sandro mi chiav&ograve; in maniera dolce, sentivo un lento va e vieni dentro il mio culo, ero eccitato al massimo. Venni quando sent&igrave;i un getto caldo dentro le mie viscere, credo che fu lo sfregamento del suo cazzo nella parete interna a portarmi all&rsquo;orgasmo, o forse fu tutta la situazione.</p>
<h2 style="text-align: center;"><strong>Chiama subito: <a href="tel:899.89.82.88" data-track-content="" data-content-name="899898288" data-content-piece="www.raccontierotici24.it">899.89.82.88</a></strong></h2>
<p><img src="/storage/chicon.png" alt="svizzera" width="26" height="17" /> Per accedere alle chiamate erotiche dalla Svizzera componi i seguenti numeri:</p>
<ul>
<li>CHIAMATE EROTICHE ETERO: <a style="font-size: 15px;" href="tel:0906.906.901" data-track-content="" data-content-name="0906906901" data-content-piece="www.raccontierotici24.it"> 0906.906.901</a> A 0,99 CHF AL MINUTO</li>
<li>CHIAMATE EROTICHE MATURE: <a style="font-size: 15px;" href="tel:0906.906.666" data-track-content="" data-content-name="0906906666" data-content-piece="www.raccontierotici24.it">0906.906.666</a> A 0,99 CHF AL MINUTO</li>
<li>CHIAMATE EROTICHE TRANS: <a style="font-size: 15px;" href="tel:0906.869.869" data-track-content="" data-content-name="0906869869" data-content-piece="www.raccontierotici24.it"> 0906.869.869</a> A 0,99 CHF AL MINUTO</li>
</ul>
<p>Da allora, sono passati tre anni e mezzo, viviamo insieme. I ruoli sono definiti. A me piace la passivit&agrave; e lui a chiavarmi e lo fa in maniera divina. A volte mi chiede di impalarmi da solo, io seduto sopra la sua verga che decido il ritmo, mi piace farlo entrare dentro il mio corpo lentamente, assaporo ogni centimetro di cazzo, mentre lui mi guarda profondamente. Mi chiama la sua "troietta con il cazzo" perch&eacute; sa che non posso fare pi&ugrave; a meno della sua asta.</p>
<p>Mi piace in tutte le salse, mi piace sbocchinarlo, mi piace a volte, prenderlo mentre sono chinato a pecorina, mi piace stare con le chiappe allargate e aspettare che lui mi faccia suo.</p>
<p>Vuoi spendere di meno?</p>
<p>Componi il numero <strong><a href="tel:0689083867" data-track-content="" data-content-name="0689083867" data-content-piece="www.raccontierotici24.it">06.890.83.867</a>&nbsp;</strong>e ascolta il messaggio gratuito, risparmi fino a 50 centesimi di euro al minuto.</p>
<p><a href="tel:0689083867"><img class="alignnone size-full wp-image-101" style="display: block; margin-left: auto; margin-right: auto;" src="//www.raccontierotici24.it/wp-content/uploads/2015/08/mature-al-telefono-con-carta-di-credito.jpg" alt="mature al telefono con carta di credito" width="687" height="271" /></a></p>
<p>Siamo in simbiosi soprattutto quando m&rsquo;incula, a volte sento il mio cazzo esplodere ancora prima del suo orgasmo, questo avviene soprattutto quando mi chiava in maniera brutale, in quelle occasioni mi sento veramente una troia. A casa non ne ho parlato non capirebbero.</p>
<p>Ho, infatti, ancora rapporti con la mia famiglia d'origine cui ho anche presentato Sandro, (ma solo come amico e non come compagno), una volta mi ha persino trombato sul letto dei miei genitori, &egrave; forse stata la volta che ho provato pi&ugrave; intrigo, probabilmente perch&eacute; l'ho vissuto come gesto di estrema rivalsa.</p>
<p>A volte anche lui mi chiede di essere trombato, non mi piace particolarmente, ma lo faccio perch&eacute; sono la sua puttana con il cazzo e soprattutto perch&eacute; le puttane non &hellip;rifiutano mai niente</p>