<p>Sono un uomo di 36 anni e da un anno e mezzo sono sposato e ho iniziato a convivere con la mia splendida moglie di 34 anni. Siamo una coppia affiatata e che ha una notevole sintonia, anche sotto le lenzuola: posso dire che non ci facciamo mai mancare nulla, entrambi siamo soddisfatti l'uno dell'altro.</p>
<p>Amiamo sperimentare sempre nuove esperienze sessuali dando spazio sempre alla nostra fantasia: devo ammettere che le abbiamo provate tutte e sono felicissimo dei nostri momenti passionali. Da qualche tempo per&ograve;, abbiamo scoperto una pratica sessuale che ci ha davvero interessati moltissimo e che abbiamo trovato entrambi soddisfacente, ovvero l'incesto. Fino a qualche tempo fa, solo pensare ad una cosa del genere non era da me, ma oggi ogni volta che penso ai momenti vissuti mi prende una grande eccitazione e voglia di avere un rapporto sessuale molto trasgressivo.</p>
<p>Tutto inizia con il trasferimento di mia suocera a casa dovuto a dei problemi nella sua casa vecchia. Mai scelta fu pi&ugrave; felice per noi sia come coppia sia come famiglia per ravvivare la nostra vita passionale. Gi&agrave; da tempo notavo nella mamma di mia moglie un certo desiderio di trasgressione che, a quanto mi ha riferito la figlia, &egrave; stato conseguenza diretta della prematura perdita del marito. Mia moglie Raffaella e sua madre Rosa hanno sempre avuto un rapporto molto stretto: &egrave; stata proprio lei a sapere la prima volta mia e di Raffaella.</p>
<p>D'altronde Rosa ha sempre amato dare i consigli piccanti a sua figlia, proprio per rendere il rapporto ancor pi&ugrave; frizzante e passionale. Ma non finisce qui, in quanto mia suocera &egrave; anche una splendida donna di 64 anni con un corpo che dimostra molti anni di meno: in molti per strada pensano sia una donna di quarant'anni e la cosa non pu&ograve; che farle enormemente piacere. Anche io non ho mai potuto fare a meno di notare il suo corpo e le sue forme estremamente eccitanti. Pi&ugrave; volte mi sono soffermato a guardare il suo seno ed il suo lato b e non nascono che &egrave; capitato che i nostri sguardi si incrociassero e lei sembrava gradire il mio apprezzamento. Ma soprattutto, la cosa particolare l'ho notata qualche mese fa, quando mia moglie Raffaella si accorse di qualche sguardo tra me e sua madre e sembrava gradire la cosa.</p>
<p>Infatti dopo qualche giorno ci ritrovammo a parlarne e lei vedeva questa cosa di buon occhio anche per aiutare la mamma che amava sentirsi desiderata dagli uomini nonostante l'et&agrave;. Col passare del tempo, la convivenza in casa &egrave; diventata sempre pi&ugrave; bollente: mia moglie mi ha sempre messo in guardia avvertendomi di come lei e sua madre fossero totalmente disinibite. Raffaella gira spesso in casa in intimo o addirittura senza soprattutto dopo aver fatto una doccia, ma non sono potuto rimanere che a bocca aperta quando una sera mi ritrovai mia suocera uscire dal bagno completamente nuda.</p>
<p>Ho potuto ammirare il suo splendido seno ed un lato b da paura, oltre a delle gambe sensuali. In quel momento mi prese un'erezione evidente pur indossando il pantalone e lei not&ograve; la cosa e sorrideva. Preso dalla foga e dal desiderio andai in camera da letto dove si trovava mia moglie Raffaella. Non le ho dato neanche il tempo di infilarsi gli slip che subito l'ho presa e abbiamo fatto l'amore in modo passionale, proprio come piaceva a noi.</p>
<p>La situazione pi&ugrave; piccante, per&ograve; successe dopo qualche giorno. Ormai mi ero abituato a vedere mia moglie e mia suocera girare per casa nude o seminude e anche io non avevo problemi a mostrarmi come mamma mi ha fatto. Una sera non ho potuto resistere e vidi la porta della camera di mia suocera socchiusa e la guardai in tutta la sua bellezza mentre dormiva, completamente nuda sul letto.</p>
<p>Non aveva nulla ed ero affascinato come non mai da tutto di lei: dal seno prosperoso ad un lato b sexy, fino a passare a dei piedi curati e sempre profumati. La voglia di possederla e farci l'amore era tanta ma non avrei mai potuto fare un pensiero del genere sulla mamma di mia moglie. Lei dormiva ancora, cos&igrave; andai in camera da letto e con mia moglie Raffaella iniziammo a toccarci proprio come succede prima che iniziamo a fare l'amore.</p>
<p>Io ero completamente nudo ed avevo un'erezione assurda, mentre mia moglie era rimasta soltanto con uno dei suoi perizomi sexy che indossava quando veniva a letto con me. Mentre ci baciamo e ci tocchiamo vedo comparire sull'uscio della porta Rosa, mia suocera, completamente nuda. A quella visione non mi sentii per niente inibito e anzi mi eccitai ancora di pi&ugrave;. Vedendola nuda sedersi sul nostro letto ho potuto toccare con mano cosa vuol dire raggiungere l'apice dell'eccitazione.</p>
<p>Io e mia moglie Raffaella iniziammo a fare sesso avanti a lei. Rosa restava seduta, con una gamba appoggiata per terra ed una sul letto. Avevo un suo piede nudo vicino alla faccia mentre facevo sesso con Raffaella e lei inizi&ograve; a strofinarmelo sul viso, passando poi ad accarezzare in modo sensuale il seno di sua figlia Raffaella.</p>
<p>Non ci siamo riusciti a fermare e per tutti e tre &egrave; stato un momento di passione incredibile. Mia moglie Raffaella, dopo aver raggiunto l'orgasmo, si &egrave; stesa e ha iniziato a toccare la madre che nel frattempo toccava il mio organo. Fu difficilissimo mantenere la calma e finii per fare sesso anche con mia suocera, con mia moglie che guardava e si toccava nel frattempo. Esperienze che non dimenticher&ograve; mai e che mi hanno permesso di scoprire una nuova frontiera dell'eros.</p>
<p>Vuoi spendere di meno?</p>
<p>Componi il numero&nbsp;&nbsp;<strong><a href="tel:0689083867" data-track-content="" data-content-name="0689083867" data-content-piece="www.raccontierotici24.it">06.890.83.867</a>&nbsp;</strong>e ascolta il messaggio gratuito, risparmi fino a 50 centesimi di euro al minuto.</p>
<p><a href="tel:0689083867"><img class="alignnone size-full wp-image-101" style="display: block; margin-left: auto; margin-right: auto;" src="//www.raccontierotici24.it/wp-content/uploads/2015/08/mature-al-telefono-con-carta-di-credito.jpg" alt="mature al telefono con carta di credito" width="687" height="271" /></a></p>