<p>Un citofono con su la scritta &lsquo;interno A&rsquo; mi aveva reso dubbioso sulle mie intenzioni.</p>
<h2 style="text-align: center;"><strong>Chiama subito: <a href="tel:899.89.82.45" data-track-content="" data-content-name="899898245" data-content-piece="www.raccontierotici24.it">899.89.82.45</a></strong></h2>
<p><img src="/storage/chicon.png" alt="svizzera" width="26" height="17" /> Per accedere alle chiamate erotiche dalla Svizzera componi il seguente numero:</p>
<ul>
<li>CHIAMATE EROTICHE TRANS: <a style="font-size: 15px;" href="tel:0906.869.869" data-track-content="" data-content-name="0906869869" data-content-piece="www.raccontierotici24.it"> 0906.869.869</a> A 0,99 CHF AL MINUTO</li>
</ul>
<p>Ero un uomo di successo e, come un etero convinto, mi divertivo a fare sesso con chiunque mi capitasse a tiro e, confesso, di aver avuto fino a quel momento, un certo successo. Sicuramente era frutto della mia posizione di imprenditore conosciuto nel suo ambiente ma, soprattutto dalla mia capacit&agrave; di capire le psiche delle donne che incontravo e di maneggiare la mia personalit&agrave; al fine di farla risultare pi&ugrave; che affascinante.</p>
<p>L&rsquo;idea di andare con un trans era nata poco a poco e, probabilmente fu originata dall&rsquo;incontrare degli splendidi esemplari durante le mie notti cittadine quando incontravo bei trans prostituirsi per le vie del centro.</p>
<p>Incominciai a pensare quale nuova sensazione avrei potuto vivere, facendo sesso con uno di loro ma l&rsquo;idea di rimorchiarli in macchina per avere uno scomodo rapporto al quale mi ero disabituato con il tempo, non aiutava la mia voglia di azione.</p>
<h2 style="text-align: center;"><strong>Chiama subito: <a href="tel:899.89.82.88" data-track-content="" data-content-name="899898288" data-content-piece="www.raccontierotici24.it">899.89.82.88</a></strong></h2>
<p><img src="/storage/chicon.png" alt="svizzera" width="26" height="17" /> Per accedere alle chiamate erotiche dalla Svizzera componi i seguenti numeri:</p>
<div class="uk-grid-divider uk-child-width-expand@s" uk-grid><div><p class="uk-text-center">CHIAMATE EROTICHE ETERO: <a style="font-size: 15px;" href="tel:0906.906.901" data-track-content="" data-content-name="0906906901" data-content-piece="www.raccontierotici24.it"> 0906.906.901</a> A 0,99 CHF AL MINUTO</p></div>
<div><p class="uk-text-center">CHIAMATE EROTICHE MATURE: <a style="font-size: 15px;" href="tel:0906.906.666" data-track-content="" data-content-name="0906906666" data-content-piece="www.raccontierotici24.it">0906.906.666</a> A 0,99 CHF AL MINUTO</p></div>
<div><p class="uk-text-center">CHIAMATE EROTICHE TRANS: <a style="font-size: 15px;" href="tel:0906.869.869" data-track-content="" data-content-name="0906869869" data-content-piece="www.raccontierotici24.it"> 0906.869.869</a> A 0,99 CHF AL MINUTO</p></div></div>
<hr>
<p>Fu solo leggendo alcuni annunci economici che mi resi conto che esisteva anche un&rsquo;alternativa che avrebbe reso possibile il fare quell&rsquo;esperienza. Composi il numero di cellulare ma, anzich&eacute; ricevere risposta, si azion&ograve; un nastro registrato dove una voce dalla pronuncia brasiliana invitava a recarsi presso un certo indirizzo e citofonare ad un anonimo interno A.</p>
<p>Ora, davanti a quella targhetta trasparente, mi stavano salendo tutte le paure possibili che attraversavano il mio cervello ma alle quali diedi un taglio netto premendo il citofono. Immediatamente si apr&igrave; una porta e una voce mi disse di prendere la rampa che conduceva al sottoscala, cosa che feci con poca baldanza mentre continuavo a dubitare della mia sessualit&agrave;.</p>
<p>Si socchiuse una porta e una visione angelica apparve in mia attesa. Confesso che per quante donne avessi frequentato, questa era indescrivibilmente bella. Una pelle vellutata color ambra ancora pi&ugrave; evidenziata da un completo intimo bianco avorio di pizzo accompagnato da autoreggenti dello stesso colore, un viso che risultava un equilibrato mix tra un angelo e una porca incorniciato da lunghi capelli neri leggermente mossi e che vedeva una rossa bocca che si apriva ad un malizioso sorriso che valeva pi&ugrave; di mille parole, rappresentavano quella visione che mi accolse con un &lsquo;ciao&rsquo; appena sussurrato.</p>
<p>Il piccolo ingresso dava su un altro ambiente che era celato alla vista da una porta chiusa e sulla camera da letto arredata piuttosto elegantemente.</p>
<p>Tizy, come disse di chiamarsi, mi invit&ograve; a bere un drink che cortesemente rifiutai e mi accarezz&ograve; all&rsquo;altezza della patta dei pantaloni suscitando una prima reazione del mio uccello. Dolcemente mi spogli&ograve; prima di slacciarsi il corpetto che lasci&ograve; liberi due seni perfetti che sapevo essere il risultato di una ovvia operazione di chirurgia plastica ma che non vedevo l&rsquo;ora di succhiare golosamente.</p>
<p>Senza molte parole mi fece stendere sul letto dove si impossess&ograve; della mia verga, avvolgendola in un bacio che somigliava pi&ugrave; ad una ventosa che ad una tenera effusione. Poi, in silenzio, si sfil&ograve; il tanga lasciando emergere una verga che si andava ad ingigantire a vista d&rsquo;occhio e che mi lasci&ograve; interdetto pensando alle misure del mio cazzo.</p>
<p>Ma oltre essere lunga, presentava un diametro notevole che incuteva pi&ugrave; che rispetto. Eppure, pensai, un corpo di donna come quello avere quell&rsquo;uccello clamoroso era davvero curioso. Mi resi conto che lo strofinio del suo cazzone alimentava la mia eccitazione anche grazie ad un pompino magistrale che mai nessuna donna mi aveva fatto in quel modo.</p>
<p>Poi, poco a poco il trans riusc&igrave; a guadagnare la posizione del 69 per la quale vedevo la sua possente minchia aleggiare pericolosamente sopra il mio viso tanto da sentirla alcune volte sfiorarmi le labbra. La voglia si fece irrazionale e decisi di prendere il coraggio a due mani, anche se con due mani afferrai ben altro e cos&igrave; cominci&ograve; la mia esperienza vera con il trans.</p>
<p>Il suo cazzo mi riemp&igrave; la bocca lasciandomi senza fiato ma ci&ograve; che razionalmente mi fu chiaro &egrave; il fatto che pi&ugrave; lo spampinavo e pi&ugrave; ne avevo il desiderio come un affamato che anzich&eacute; saziarsi mangiando, avverte ancor di pi&ugrave; i morsi della fame. La bellissima trans smise di fare il 69 e si mise a pecorina offrendomi il suo perfetto culo tutto da penetrare, cosa che feci senza indugio trovando accogliente quel rifugio che mi forniva tutto il piacere di cui avevo bisogno ma l&rsquo;esperto trans decise che era giunta l&rsquo;ora di farmi provare l&rsquo;ultima emozione che ancora dovevo vivere.</p>
<p>Cambiando posizione mi fece distendere sul letto poi mi alz&ograve; le gambe divaricandole bene al fine di lasciare il mio culo senza alcuna difesa e dopo averlo baciato e leccato per umidificarlo, cominci&ograve; a metterci dentro quel suo cazzo duro facendomi male. Per&ograve; confesso che quella sofferenza si tramut&ograve; in sordo piacere in una dimensione mai vissuta prima di allora che compensava la mia parte femminile del mio DNA e, anche in quel caso, pi&ugrave; mi sbatteva e pi&ugrave; mi piacere essere sbattuto. La fine di quella prima esperienza fu il perfezionamento del 69 incominciato prima dove mi abbeverai di una marea di calda sborra proprio mentre stavo schizzando anch&rsquo;io dentro alla sua bocca.</p>
<p>Richiudendo dietro di me la porta, mi trovai soddisfatto e totalmente appagato e compresi che il sesso non poteva avere limiti di sorta ma che, purtroppo, era condizionato da una serie di prevenzioni ipocrite che dovevano forzatamente essere mantenute per una questione di apparenze sterili e idiote. Risalendo in auto pensai al perch&eacute;, file di auto si accalcavano ogni notte su quei viali mal illuminati per far salire a bordo uno di quei trans che battevano la strada e che si apprestavano ad essere degli anonimi strumenti di un rapido e frugale piacere.</p>
<p>Riconsiderai le mie posizioni prima di quella esperienza che, oltre che estremamente piacevole, era stata fortemente illuminante e che certamente avrei voluto rivivere per provare le stesse identiche sensazioni che coniugavano una ridda di desideri e di modi per procurarsi piacere. Una prova che non mi sono mai pentito di aver fatto anche se, resta un mio segreto inconfessato.</p>