<p>Il mio ricordo è legato alla giovinezza, quando ero poco più che diciottenne, e mi sentivo padrone del mondo, avevo preso la patente, avevo avuto le mie prime esperienze sessuali, e tutto andava per il verso giusto, ero felice della mia vita.</p>

<p>Abitavo ancora con i miei genitori, nel palazzone in pieno centro a Roma, era in un bel quartiere residenziale, tutta brava gente, a posto, che lavorava sodo per arrivare a fine mese, senza tanti grilli per la testa, tutti, o quasi tutti.</p>

<p>Una persona era diversa da tutte le altre, sembrava capitata lì per caso, quasi caduto sulla terra ed atterrato nel nostro palazzone, era di un'altra estrazione sociale, si vedeva lontano un miglio. Si chiama Fiorenzo, per tutti famigliarmente Renzo, ed era un signore di mezz'età, gentile, distinto, sempre ben vestito, spesso in giacca e cravatta, si diceva che facesse l'agente di commercio, aveva anche una gran bella macchina, una Audi A6 nuova di pacca.</p>

<p>Veramente qualcosa di stonato ce l'aveva Renzo, e le voci nel quartiere giravano, e giravano, i soliti bene informati dicevo che avesse strane tendenze, che non lo si vedeva mai in compagna di una donna, che i suoi modi gentili nascondessero qualcosa, che insomma fosse un gay.
Io non prestano particolare attenzione a queste chiacchiere, quando lo incrociavo, lo salutavo senza problemi, fino al giorno in cui non salimmo in ascensore insieme.</p>

<p>Aveva due borse belle piene, l'ascensore era un po' vecchiotto e piccolino, conteneva al massimo quattro persone, mi fece accomodare per primo, sia per l'animo cortese, sia perché abitava al piano di sotto, lui abitava al quinto piano, io al sesto con i miei genitori. Schiacciai i pulsanti e l'ascensore cominciò a salire, ma, dopo una partenza incerta, ebbe uno scossone, che fece perdere l'equilibrio al signor Renzo, che mi piombò addosso.</p>

<p>Nel tentativo di recuperare stabilità, il signore appoggiò una mano sulla mia patta, cercando di aggrapparsi al mio uccello, cosa che gli riuscì, sentii chiaramente la sua mano stringersi sul mio membro. Non diedi molta importanza al fatto, pensando che fosse legato all'improvviso sbandamento, se non fosse per quell'ultima palpatina data al mio cazzetto, che stranamente aveva gradito le sue attenzioni. Si scusò per l'accaduto, chiedendomi se poteva offrirmi un caffè nel suo appartamento. Preso alla sprovvista, non sapevo cosa fare, ma un buon caffè mi andava proprio, e visto che erano le cinque del pomeriggio, accettai di buon grado, in fondo cosa poteva capitarmi.</p>

<p>Renzo era felice della mia risposta, si affrettò ad aprire la porta di casa, e mi fece entrare. Bello, finemente arredato, per nulla parente del nostro tranquillo appartamento del piano di sopra, disposto diversamente, forse di superficie leggermente inferiore. Renzo mi portò subito il caffè, chiedendomi se volevo qualche tipo di correzione, risposi che un goccio d'anice andava bene. </p>

<p>Mi porse il caffè corretto, sempre con i suoi modi affabili, era affascinante nei suoi movimenti, non capivo perché mi piacesse il suo incedere ma era così, inutile negarlo. Stavo prendendo il mio buon caffè, quando qualcosa mi sfiorò una gamba, facendomi sobbalzare e gridare, perché un po' di caffè mi cadde proprio sulla patta dei jeans: era il suo gattone nero, che passando tra le mie gambe, mi aveva fatto versare dell'aromatico liquido nero sul mio pistolino. </p>

<p>Era ancora molto caldo, Renzo era nuovamente dispiaciuto, e qualche naturalmente mi slacciò i pantaloni, e vedendo che il caffè era passato sotto, mi abbassò anche gli slip, esponendo il mio cazzo al suo sguardo. </p>

<p>La situazione era imbarazzante, Renzo lo guardava intensamente, era abbastanza chiaro quali fossero le sue intenzioni, ed infatti dopo qualche secondo allungò una mano, prendendolo in mano. Ero bloccato, non sapevo cosa fare, avrei voluto allontanarlo ma stranamente la situazione era intrigante, non mi dispiaceva più di tanto. </p>

<p>Lo guardai in viso, era eccitatissimo in ginocchio davanti a me, con il mio cazzo in mano, lui prese al volo l'occasione e diresse il viso verso il suo oggetto del desiderio, e iniziò a succhiarmelo, prima timidamente, poi sempre più avidamente, iniziando un vero e proprio pompino. Forse era troppo, provai a fermarlo, e lui la suzione, prendendomi per mano e portandomi nella sua bellissima camera da letto, la sua peccaminosa alcova. </p>

<p>Mi fece sedere sul letto, sfilandomi completamente i pantaloni e gli slip, offrendomi un amaro, così, giusto per rompere definitivamente il ghiaccio, e probabilmente per darmi il coraggio di compiere il grande passo. Sorseggiai il superalcolico, io che ero quasi astemio, ma ne avevo proprio bisogno, e dopo averlo terminato, Renzo mi distese sul letto, chiedendomi di lasciarmi andare, che non me ne sarei pentito. Provai ad ascoltarlo, e lo assecondai. Mi allargò leggermente le gambe, mi chiedevo cosa volesse fare, e riprese a succhiarmi il cazzo, con rinnovato vigore, ed il mio uccello rispose alla stimolazione, raggiungendo la piena erezione dentro alla sua sapiente bocca. </p>

<p>Era bravissimo, nettamente il miglior pompino che avessi mai ricevuto nella mia breve carriera scopatoria, aspirava la mia cappella con una maestria unica, massaggiava le mie palle esercitando una dolce pressione, tutto molto bello, finché non avvertii una fitta nel culetto, un piccolo, leggero bruciore: mi aveva infilato un dito, con la velocità della luce, aveva deflorato il mio piccolo orifizio, e se ne stava lì, in attesa della mia reazione. Il mio sederino si stava abituando in fretta, al punto tale che non opposi più resistenza, rilassando completamente lo sfintere, cosa che Renzo notò subito, riprendendo a pompare il mio cazzo in bocca e spingendo sù e giù il dito.</p>

<p>Era tutto delizioso, la sua bocca, il dito nel culo, godevo da matti, e sentivo la sborra salire nel cazzo, e dopo un paio di minuti riversai un bel fiotto di caldo sperma nella bocca di Renzo, che trattene tutto, raccogliendo ogni singola goccia, e staccandosi dal mio cazzetto, mi guardò negli occhi, e in un colpo solo, ingoiò tutta la mia consistenza vischiosa. Cazzo, aveva bevuto tutta la mia sborra, incredibile, nessuna ragazza aveva fatto tanto, anzi, alla fuoriuscita del mio liquido seminale, si staccavano schizzinose, Renzo no, Renzo aveva degustato il mio sperma. Mi guardò nuovamente negli occhi, e dolcemente mi girò a pancia sotto, chiedendomi se andava tutto bene. </p>

<p>Pieno della scena precedente, risposi di sì, e Renzo mi pregò di sollevare leggermente la pancia, in modo da permettergli di piazzare sotto di me un paio di cuscini. Avevo il culetto orrendamente esposto alla sua vista, intuivo cosa stava per fare Renzo, ma ripensandoci, ero molto tranquillo, non mi era capitato nulla di male, mi era piaciuto praticamente tutto, e cercavo solo di essere rilassato. Renzo prese qualcosa, sentivo svitare un coperchio, e mi massaggiò i coglioni, riprendendo a segare il cazzo, che rispondeva agli stimoli, e cominciò a leccarmi il buco del culo. </p>

<p>Sapeva fare anche quello, mi piaceva tutto, la lingua, il massaggio, la sega, era favoloso, e quando la lingua terminò il suo lavoro, capii che il momento del grande passo era giunto, Renzo era sul punto di mettermi il cazzo nel culo.</p>

<p>Respirai a fondo, avvertii chiaramente la sua cappella premere contro il mio sfintere, e dopo qualche secondo era già entrata, grazie all'ottima lubrificazione. Renzo restò un po' di tempo fermo in quella posizione, continuando a segarmi il cazzo, poi iniziò a premere con maggiore vigore, e le pareti del mio culetto cominciarono a cedere piano piano, e il suo cazzo si faceva strada dentro me, sempre più a fondo. Con un ultimo colpo finale, le sue palle toccarono le mie, era totalmente entrato con tutta la minchia nel mio culetto, e mi piaceva, e parecchio. </p>

<p>Iniziò a regolare i colpi di cazzo con la masturbazione del mio uccello, era la fine del mondo, godevo nel culo, godeva il mio cazzo, non avevo mai provato una sensazione tale, avevo il culo in fiamme, era la prima volta per me, ma il piacere aveva il sopravvento su tutto. Renzo era un professionista, avvertì chiaramente il sopraggiungere del mio secondo orgasmo e quasi simultaneamente inondò il mio culo con la sua sborra, riempiendomi le viscere fino in fondo, ed io sborrai sul tuo letto, con schizzi potentissimi, aiutato dal pompaggio nel culo. Fu molto dolce nell'estrarre il suo cazzo dal culo, ed altrettanto dolce fu nel porgermelo sulle labbra, voleva che lo succhiassi, non potevo rifiutare, era stato troppo bravo. </p>

<p>Glielo leccai, non ero molto bravo, ma Renzo aveva troppa voglia, e mi prese la testa tra le mani, scopando letteralmente la mia bocca, e dopo poco inarcò la schiena, strinse le sue mani sui miei capelli, e mi sborrò dentro la gola, tutto lo sperma che poteva, finché mi sdraiò accanto a me, accarezzandomi dolcemente l'uccello, baciandomi sulla bocca.</p>

<p>Componi il numero&nbsp;&nbsp;<strong><a href="tel:0689083867" data-track-content="" data-content-name="0689083867" data-content-piece="www.raccontierotici24.it">06.890.83.867</a>&nbsp;</strong>e ascolta il messaggio gratuito, risparmi fino a 50 centesimi di euro al minuto.</p>
<p><a href="tel:0689083867"><img class="alignnone size-full wp-image-101" style="display: block; margin-left: auto; margin-right: auto;" src="//www.raccontierotici24.it/wp-content/uploads/2015/08/mature-al-telefono-con-carta-di-credito.jpg" alt="mature al telefono con carta di credito" width="687" height="271" /></a></p>