<p>Quando non ho potuto pi&ugrave; evitare di tornare al mare con i miei vecchi amici ho dovuto affrontare mio marito e dirgli che per una volta avrei voluto partire da sola.</p>
<p>Avevo preparato una risposta convincente per ogni sua possibile obiezione, ma non ero preparata ad ascoltare la singola, enorme e potente parola che mi disse con un sorriso di soddisfazione stampato sul viso: finalmente!</p>
<h2 style="text-align: center;"><strong>Chiama subito: <a href="tel:899.89.82.88" data-track-content="" data-content-name="899898288" data-content-piece="www.raccontierotici24.it">899.89.82.88</a></strong></h2>
<p><img src="//www.raccontierotici24.it/storage/chicon.png" alt="svizzera" width="26" height="17" /> Per accedere alle chiamate erotiche dalla Svizzera componi i seguenti numeri:</p>
<ul>
<li>CHIAMATE EROTICHE ETERO: <a style="font-size: 15px;" href="tel:0906.906.901" data-track-content="" data-content-name="0906906901" data-content-piece="www.raccontierotici24.it"> 0906.906.901</a> A 0,99 CHF AL MINUTO</li>
<li>CHIAMATE EROTICHE MATURE: <a style="font-size: 15px;" href="tel:0906.906.666" data-track-content="" data-content-name="0906906666" data-content-piece="www.raccontierotici24.it">0906.906.666</a> A 0,99 CHF AL MINUTO</li>
<li>CHIAMATE EROTICHE TRANS: <a style="font-size: 15px;" href="tel:0906.869.869" data-track-content="" data-content-name="0906869869" data-content-piece="www.raccontierotici24.it"> 0906.869.869</a> A 0,99 CHF AL MINUTO</li>
</ul>
<p>Eh s&igrave;, il mio caro uomo con cui vivevo insieme da diversi anni mi spieg&ograve; che gli sembrava strano che ancora non fosse nata questa esigenza e che &egrave; una scelta ottima per il benessere della coppia. Non me lo feci ripetere, chiamai Carlo e Mario per avvisarli che sarei andata e organizzai il viaggio in un'ora. In albergo svuotai la valigia e trovai un pacchetto con un bigliettino, era di mio marito. C'era scritto che non gli piacevano i costumi che avevo portato con me e che aveva provveduto a regalarmene qualcuno.</p>
<p>Gli avrebbe fatto piacere ricevere qualche mia foto sulla spiaggia con quei suoi regali. Mi ritrovai davanti tre piccole confezioni che mi lasciarono senza parole. Nella prima c'era un bikini arancione estremamente piccolo e piuttosto trasparente, nel secondo un costume intero bianco con stampata la parole Felicit&agrave;, infine un tanga bianco completamente trasparente e talmente piccolo da non sapere come fare a non farlo sprofondare tra le mie grandi labbra.</p>
<p>Vuoi spendere di meno?</p>
<p>Componi il numero&nbsp;&nbsp;<strong><a href="tel:0689083867" data-track-content="" data-content-name="0689083867" data-content-piece="www.raccontierotici24.it">06.890.83.867</a>&nbsp;</strong>e ascolta il messaggio gratuito, risparmi fino a 50 centesimi di euro al minuto.</p>
<p><a href="tel:0689083867"><img class="alignnone size-full wp-image-101" style="display: block; margin-left: auto; margin-right: auto;" src="//www.raccontierotici24.it/wp-content/uploads/2015/08/mature-al-telefono-con-carta-di-credito.jpg" alt="mature al telefono con carta di credito" width="687" height="271" /></a></p>
<p>Lo chiamai con un finto tono risentito, in realt&agrave; era eccitazione allo stato puro, conclusi la telefonata dicendogli che non sapevo se avrei indossato quei costumi indecenti. Mentivo, ma non avevo il coraggio di confessargli che la cosa mi faceva impazzire dal piacere. Chiamai Carlo per accordarmi sul quando e dove vederci e per prepararlo alla richiesta di mio marito, compreso il suo desiderio di ricevere qualche mia foto in costume.</p>
<p>Scelsi il costume intero, non mi pareva il caso di mostrarmi subito del tutto nuda ai miei amici e alle centinaia di persone presenti sulla spiaggia: un minimo di ambientamento! Appena uscita dall'acqua capii che avevo compiuto la scelta peggiore, il tessuto scompar&igrave; quasi del tutto lasciandomi completamente nuda mentre tornavo verso la sdraio. Mario, che dei due &egrave; quello privo di tab&ugrave;, mi fotograf&ograve; e chiese il numero di mio marito per inviargli la foto, non avevo motivo di negarglielo. Quando Mario ricevette la risposta rimase per qualche secondo in silenzio prima di passare il cellulare a Carlo che a sua volta lesse e mi guard&ograve; sorpreso.</p>
<p>Tocc&ograve; a me leggere le parole di mio marito che esaltavano il mio corpo meraviglioso e che augurava a tutti e tre di divertirci il pi&ugrave; possibile giorno e notte, senza limiti. Incredibile, aveva appena detto ai mie amici che da parte sua non c'erano problemi a scoparmi e a me che avevo tutta la libert&agrave; di farlo. Chiesi ai ragazzi di scusarlo ma loro risposero che volevano semmai ringraziarlo, e dicevano sul serio. Avrei voluto dire loro che no, non volevo certo fare sesso con loro ma il costume invisibile mostr&ograve; le labbra della mia fica completamente gonfie, cosa che venne notata dai due e non mi permise di replicare.</p>
<p>Mario mi prese per mano e disse di seguirlo, feci solo in tempo a coprirmi con un copricostume prima di ritrovarmi nuda sul suo letto nella stanza d'albergo. Mi prese come se non aspettasse altro dalla vita, sentivo lo sbattere del suo corpo sul mio mentre mi annientavo attorno al suo sesso. Una volta finito chiese se volessi che andasse a chiamare Carlo, annu&igrave; imbarazzata. Appena il tempo di sistemarmi che sentii entrare l'altro amico visibilmente eccitato. Restai a fissarlo per qualche secondo poi mi inginocchiai e iniziai a succhiarlo lentamente.</p>
<p>Dopo poco pi&ugrave; di un'ora ero di nuovo in spiaggia per riposarmi un po' tra i miei due meravigliosi amanti. Chiesero degli altri costumi ricevuti in regalo e proposero immediatamente il micro tanga bianco per il pomeriggio. Non desideravo altro. Cos&igrave; dopo poche ore mi ritrovai in spiaggia in topless e un tanga quasi del tutto inesistente.</p>
<p>Mario non seppe resistere alla tentazione di inviare una nuova foto a mio marito che per tutta risposta chiese se l'altro costume non si fosse gi&agrave; sporcato, il che convinse i miei amici che lui voleva proprio che io trascorressi le vacanze a scopare con loro e che erano disposti, dolci anime pie ed altruiste, ad esaudire il suo desiderio trasgressivo.</p>
<p>Carlo propose di cenare insieme e magari di salire tutti insieme nella sua stanza. La scomparsa nel mio sesso di quel pezzettino di stoffa che mi ostinavo a chiamare costume diede la risposta che si aspettavano. Mangiammo con calma, per giocare con l'attesa, e quando entrai nella camera di Carlo mi spogliai immediatamente per lasciare che spegnessero la mia voglia senza pi&ugrave; pudore. Una volta salita su Carlo che si era disteso sul letto iniziai un lento su e gi&ugrave; per stuzzicare lo sguardo di Mario che era rimasto in disparte a guardare, fino a quando sentii la sua mano spingere delicatamente la mia schiena verso il basso e capii che la sua intenzione era di mettermi al centro di una doppia penetrazione.</p>
<p>Infatti, pochi secondi dopo mi ritrovai con entrambi i peni dentro di me. Si fermarono, Mario pos&ograve; il cellulare accanto alla testa di Carlo in modo che io vedessi che sarebbe bastato premere un tasto per inviare a mio marito il filmato di quell'inizio di scopata. Diedi un profondo bacio a Carlo, allungai la mano e dopo pochi secondi il video di due uomini che mi stavano scopando arriv&ograve; nelle mani di mio marito.</p>
<p>Spostai lo smartphone e lasciai che il mio corpo assaporasse ogni centimetro dei miei amanti.</p>