<p>Era l'inizio dell'estate, e come ogni anno in famiglia, si decise dove trascorrere le classiche vacanze estive.</p>
<p>La mia famiglia &egrave; composta da 4 persone persone, mio padre un uomo di media statura con occhi castani e capelli neri, per capire meglio il tipo immaginate il classico mediterraneo, mia sorella una ragazza di 21 anni, capelli biondi, una quarta di seno, e un fondoschiena davvero da far paura, mia madre una donna di 51 anni, che per caratteristiche personali ancora riesce a farsi notare, soprattutto per il suo modo di vestire sempre molto provocante, si tratta di una donna alta circa 170 cm, capelli biondi, una quarta di seno, un bel culo sempre sodo, soprattutto grazie al fatto che frequenta la palestra tutto l''anno, e delle labbra carnose, insomma in poche parole la classica "Milf porcellina", e infine ci sono io un ragazzo di 29 anni capelli mori magro e alto 180.</p>
<p>Vuoi spendere di meno?</p>
<p>Componi il numero <strong><a href="tel:0689083867" data-track-content="" data-content-name="0689083867" data-content-piece="www.raccontierotici24.it">06.890.83.867</a>&nbsp;</strong>e ascolta il messaggio gratuito, risparmi fino a 50 centesimi di euro al minuto.</p>
<p><a href="tel:0689083867"><img class="alignnone size-full wp-image-101" style="display: block; margin-left: auto; margin-right: auto;" src="//www.raccontierotici24.it/wp-content/uploads/2015/08/mature-al-telefono-con-carta-di-credito.jpg" alt="mature al telefono con carta di credito" width="687" height="271" /></a></p>
<h2 style="text-align: center;"><strong>Chiama subito: <a href="tel:899.89.82.88" data-track-content="" data-content-name="899898288" data-content-piece="www.raccontierotici24.it">899.89.82.88</a></strong></h2>
<div class="uk-grid-divider uk-child-width-expand@s" uk-grid><div><img class="uk-align-center uk-margin-small-bottom" src="/storage/italy.png" alt="svizzera" width="26" height="17" /><p class="uk-text-center">CHIAMATE EROTICHE MATURE: <a style="font-size: 15px;" href="tel:899.37.00.32" data-track-content="" data-content-name="899370032" data-content-piece="www.raccontierotici24.it">899.37.00.32</a></p></div>
<div><img class="uk-align-center uk-margin-small-bottom" src="/storage/chicon.png" alt="svizzera" width="26" height="17" /><p class="uk-text-center">CHIAMATE EROTICHE MATURE: <a style="font-size: 15px;" href="tel:0906.906.666" data-track-content="" data-content-name="0906906666" data-content-piece="www.raccontierotici24.it">0906.906.666</a> A 0,99 CHF AL MINUTO</p></div></div>
<p>Mia madre e mia sorella, per come la vedo io, sono fatte della stessa pasta, e cio&egrave; due donne a cui piace mettersi in mostra, e che secondo me se la spassano alla grande, ovviamente all''insaputa di mio padre che &egrave; il classico marito e padre gelosissimo.</p>
<p>Per affermare ci&ograve; ho comunque le mie ragioni, soprattutto dopo quell'estate trascorsa a Malta, in compagnia della porcellina numero uno...mia madre!!!</p>
<p>Appena arrivati alla nostra meta di destinazione fummo subito accolti da un tutor, si trattava di un ragazzo di circa 35 anni, di carnagione scura, e fisico davvero statuario, dalla sua maglietta si potevano notare degli addominali da far paura, e questa cosa non sfuggi' assolutamente alla mia cara mammina, che immediatamente cerc&ograve; durante il corso del viaggio per portarci in albergo, di stare vicino al ragazzo, e soprattutto cerc&ograve; di farsi notare soprattutto con la sua buona quarta abbondante.</p>
<p>Mio padre non not&ograve; assolutamente nulla, in quanto era impegnato a chiacchierare con mia sorella, ma io che comunque sono un tipo molto attento, scorsi subito la cara mammina a cercare le mani del ragazzo, e ad scherzarci anche in maniera troppo amichevole.</p>
<p>Quel giorno il tutor ci lasci&ograve; in albergo, dicendoci che per qualunque cosa potevamo rintracciarlo, facendogli una chiamata al cellulare.</p>
<p>Elisa, &egrave; questo il nome di mamma, non perse tempo, e dopo essersi fatta una doccia e quindi sistemata un p&ograve;, decise di sua spontanea volont&agrave; di chiamare il tutor, per poter fare un giro per la citt&agrave;, e poter quindi subito prendere confidenza con la gente del posto, ovviamente il suo intento era un''altro, ma non poteva sicuramente sbandierare a tutti che voleva farsi una bella scopata con il ragazzo.</p>
<p>Quel giorno mio padre e mia sorella decisero di non uscire, in quanto avevano risentito molto del viaggio, e quindi erano stanchi, allora decidemmo di uscire io mamma e il nostro caro tutor.</p>
<div class="uk-grid-divider uk-child-width-expand@s" uk-grid><div><p class="uk-text-center">TELEFONO EROTICO ZITTO E GODI: <a href="tel:899.84.85.97">899.84.85.97</a></p></div>
<div><p class="uk-text-center">TELEFONO EROTICO CON CARTA DI CREDITO: <a style="color: #ff0000;" href="tel:06.890.838.67">06.890.838.67</a></p></div>
<div><p class="uk-text-center">TELEFONO EROTICO BASSO COSTO: <a href="tel:899.00.33.65">899.00.33.65</a></p></div></div>
<p>Da sempre nel mio intimo ho sempre sognato vedere mia madre nuda a fare sesso con un altro uomo che non sia quindi mio padre, e allora quella fu' l'occasione buona, e appena ebbi la possibilit&agrave;, con una scusa banale, li lasciai soli o per meglio dire mi allontanai da loro, ma in verit&agrave; decisi di seguirli.</p>
<p>Mi allontanai, e loro decisero di proseguire il tragitto insieme e notai subito che la porcellina di mia madre non perse tempo, e dopo circa 10 minuti di tragitto stava gi&agrave; appartata in una casa diroccata con il bel moro, a inizialmente pomiciare.</p>
<p>Ovviamente io decisi di non intervenire, volevo assolutamente gustarmi mia madre allopera con uno sconosciuto, dopo una lunga pomiciata Elisa, con le sue manine, and&ograve; subito a cercare "l'arnese" del ragazzo e appena lo tir&ograve; fuori dei pantaloni rimase sbalordita, si trov&ograve; di fronte un palo di carne lungo circa 20 cm, grosso e soprattutto duro.</p>
<p>La maialina inizi&ograve; con un bel spompinamento, e devo dire che qui l''esperienza di mamma salt&ograve; fuori, in quanto riusci' fin dalle prime leccate a far gemere il ragazzo, e in sottofondo la sentivo incitare il ragazzo a non venire, in quanto voleva assolutamente cavalcarlo.</p>
<p>Dopo circa 5 minuti di spompinamento salt&ograve; a cavallo del ragazzo, e aprendo le gambe si scorgeva una bellissima passerina, ben curata, con il pelo completamente assente, e si poteva notare il fatto che era molto bagnata.</p>
<p>Il ragazzo, che si chiamava Marco, fece una cosa che eccit&ograve; ancora di piu' mia madre, e cio&egrave; infilo 2 dita in maniera molto decisa dentro la sua passerina, e dopo essersele bagnate, le port&ograve; alla bocca di mia madre per farsele leccare, la porcellina ovviamente non esit&ograve;, e mentre leccava le sue dita, decise di impalarsi.</p>
<p class="uk-text-center"><img src="/storage/chicon.png" alt="svizzera" width="26" height="17" /> Per accedere alle chiamate erotiche dalla Svizzera componi i seguenti numeri:</p>
<div class="uk-grid-divider uk-child-width-expand@s" uk-grid><div><p class="uk-text-center">CHIAMATE EROTICHE ETERO: <a style="font-size: 15px;" href="tel:0906.906.901" data-track-content="" data-content-name="0906906901" data-content-piece="www.raccontierotici24.it"> 0906.906.901</a> A 0,99 CHF AL MINUTO</p></div>
<div><p class="uk-text-center">CHIAMATE EROTICHE MATURE: <a style="font-size: 15px;" href="tel:0906.906.666" data-track-content="" data-content-name="0906906666" data-content-piece="www.raccontierotici24.it">0906.906.666</a> A 0,99 CHF AL MINUTO</p></div>
<div><p class="uk-text-center">CHIAMATE EROTICHE TRANS: <a style="font-size: 15px;" href="tel:0906.869.869" data-track-content="" data-content-name="0906869869" data-content-piece="www.raccontierotici24.it"> 0906.869.869</a> A 0,99 CHF AL MINUTO</p></div></div>
<hr><p>Cominci&ograve; a cavalcare Marco in maniera molto selvaggia, sembrava davvero indiavolata,e il ragazzo senza piet&agrave; sferrava dei colpi molto violenti, che facevano sobbalzare la mammina, che ad ogni colpo gemeva e incitava il ragazzo a colpire sempre piu' forte.</p>
<p>Marco guard&ograve; fissa Elisa e gli disse se aveva intenzione davvero di provare qualcosa di unico, ovviamente Elisa molto incuriosita non perse tempo, e rispose con un bel...SI!!!</p>
<p>Vuoi spendere di meno?</p>
<p>Componi il numero <strong><a href="tel:0689083867" data-track-content="" data-content-name="0689083867" data-content-piece="www.raccontierotici24.it">06.890.83.867</a>&nbsp;</strong>e ascolta il messaggio gratuito, risparmi fino a 80 centesimi al minuto.</p>
<p><a href="tel:0689083867"><img class="alignnone size-full wp-image-101" style="display: block; margin-left: auto; margin-right: auto;" src="//www.raccontierotici24.it/wp-content/uploads/2015/08/mature-al-telefono-con-carta-di-credito.jpg" alt="mature al telefono con carta di credito" width="687" height="271" /></a></p>
<p>Marco la sbatt&eacute; sul letto, e dopo avergli spalancato le gambe, cominci&ograve; a cercare con il proprio "arnese" il culetto della buona e cara mammina, che accortasi dell''intenzione del ragazzo, inizialmente lo ferm&ograve;, ma successivamente, presa dall''eccitazione, decise di farsi inculare.</p>
<p>Credo che le urla di Elisa si potessero sentire anche da molto lontano, si sentiva proprio che soffriva, ma nonostante ci&ograve;, non batt&eacute; ciglio, e anzi incitava il ragazzo dicendogli di sfondarla senza piet&agrave;, Marco non si fece pregare, e con un colpo secc&ograve; infil&ograve; tutto il suo pene nel culetto di Elisa, che dal dolore quasi sveniva, credo che davvero il pene di Marco gli sia arrivato in pancia ad Elisa, che rimasse per qualche minuto tramortita.</p>
<p>Marco c'era andato giu' pesante, ma Elisa non era stata di meno, e quindi dopo essersi ripresa dallo shock, decise di farsi sborrare dal ragazzo in bocca, andando a bere tutto il "nettare" del ragazzo senza batter ciglio.</p>
<p>Dopo qualche minuto di riposo entrambi, dopo essersi fumati una bella sigaretta, si alzarono e sfiniti decisero che per oggi poteva bastare, ma erano entrambi consapevoli che nei prossimi giorni li aspettavano momenti di vero godimento.</p>