<p>Non avrei mai pensato che lasciarmi guidare da una padrona fosse cos&igrave; eccitante.</p>
<p>Se me lo avessero detto avrei sicuramente riso a crepapelle...io, l'uomo sfrontato, il latin lover tatuato che le ragazze adoravano per la sua intraprendenza, succube di una padrona con i tacchi a spillo?</p>
<p>No, mai e poi mai avrei immaginato una cosa del genere eppure, quell'essere a quattro zampe accucciato vicino la poltrona della splendida Eliana, sono proprio io!</p>
<p>Pretende che io lavi i piatti vestito solo con un grembiulino bianco di trine, non vuole che indossi biancheria intima, le piace vedere il mio membro eretto mentre lei accavalla le gambe sul tavolo di legno massello.</p>
<p>Lo so che le piace vedermi arrapato ma &egrave; talmente perversa da non lasciarsi sfiorare nemmeno con un dito.</p>
<p>Mi ordina di riempire il lavello di acqua e detersivo e vuole vedere schiuma tanta schiuma, poi si avvicina a me da dietro ed immerge un dito in quell'acqua saponata ed io so gi&agrave; cosa intenzione di fare.</p>
<p>Mi ordina di divaricare le gambe ma vuole che continui contemporaneamente a lavare le stoviglie. Sento il suo medio scivolarmi nelle viscere, urlo di dolore misto a piacere. Il mio uccello sbatte contro l'anta del mobile del lavello ma lei sembra non importarsene e continua, continua fino a farmi male.</p>
<p>Resta cos&igrave; per un minuto, poi toglie quel dito e mi prende per i capelli trascinando la mia testa all'indietro lasciando che la guardi negli occhi. Sono duri, mi spaventa quello sguardo, ha in mente qualche altra mossa diabolica per farmi soffrire, conosco quella padrona intransigente che mi sottopone a mille sevizie.</p>
<p>Con la coda dell'occhio vedo che traffica nel cestino portaoggetti e mi terrorizza quel suo armeggiare alla ricerca di qualcosa. La vedo alle prese con due mollette per i panni.</p>
<p>Mi ordina di girarmi verso di lei, io la imploro, la supplico di non farmi del male ma lei sorride beffarda e senza proferire una sola parola, afferra i miei capezzoli e li stringe in quegli arnesi che fino a poco tempo prima erano solo innocui supporti.</p>
<p>Sento il suo respiro sulla mia pelle oramai sudata e attaccaticcia, la imploro di darmi la sua fighetta bagnata, le sussurro nell'orecchio che ho voglia di leccargliela, cerco di impietosirla, di farla eccitare e di cedere alle mie voglie.</p>
<p>Eliana mi guarda, e io so bene che pi&ugrave; mi vede eccitato e pi&ugrave; mi lascer&agrave; sbavare perch&eacute; queste sono state le regole fin dall'inizio della nostra storia.</p>
<h2 style="text-align: center;"><strong>Chiama subito: <a href="tel:899.89.82.88" data-track-content="" data-content-name="899898288" data-content-piece="www.raccontierotici24.it">899.89.82.88</a></strong></h2>
<p><img src="/storage/chicon.png" alt="svizzera" width="26" height="17" /> Per accedere alle chiamate erotiche dalla Svizzera componi il seguente numero:</p>
<ul>
<li>CHIAMATE EROTICHE: <a style="font-size: 15px;" href="tel://0906.906.901" data-track-content="" data-content-name="0906906901" data-content-piece="www.raccontierotici24.it"> 0906.906.901</a> A 0,99 CHF AL MINUTO</li>
</ul>
<p>Vuoi spendere di meno?</p>
<p>Componi il numero <strong><a href="tel:0689083867" data-track-content="" data-content-name="0689083867" data-content-piece="www.raccontierotici24.it">06.890.83.867</a>&nbsp;</strong>e ascolta il messaggio gratuito, risparmi fino a 80 centesimi al minuto.</p>
<p><a href="tel:0689083867"><img class="alignnone size-full wp-image-101" style="display: block; margin-left: auto; margin-right: auto;" src="//www.raccontierotici24.it/wp-content/uploads/2015/08/mature-al-telefono-con-carta-di-credito.jpg" alt="mature al telefono con carta di credito" width="687" height="271" /></a></p>
<p>Sapevo delle sue strambe voglie ma non avrei mai immaginato che fosse una padrona cos&igrave; esigente. Stasera la vedo pi&ugrave; perversa del solito ma la conosco, so che ha in mente una di quelle seratine piccanti che pianifica gi&agrave; dalla mattina.</p>
<p>Mi ordina di camminare verso la camera da letto ed io obbedisco ma quelle mollette con l'ondeggiare dei miei passi, mi danno il tormento, le sento pesanti come macigni.</p>
<p>Arriviamo in camera da letto, lei mi ordina di mettermi steso, poi chiude le tapparelle e lascia solo quel tanto di luce del lampione fuori la strada che basta per illuminare la mia verga che oramai sembra voglia scoppiare.</p>
<p>Rimango nudo come un verme mentre seguo i suoi movimenti e con una mano cerco di prendere i suoi capelli per avvicinarla a me, ma lei sfugge e accende l'abat jour sul comodino.</p>
<p>Apre un cassetto e ne trae un foulard nero, mi benda e io mi ribello ma sento subito una frustata sui testicoli che mi obbliga a tacere. Risento il rumore del cassetto che si riapre e dopo qualche interminabile attimo avverto un rumore di ferro. Ho il terrore di immaginare cosa sia ma me ne rendo subito conto quando Eliana mi obbliga a darle i polsi. Mi incatena al letto di ferro battuto, ora sono un essere inerme, Eliana pu&ograve; fare di me quello che vuole.</p>
<p>Di fronte a me c'&egrave; una cassapanca, la conosco bene perch&eacute; gi&agrave; altre volte &egrave; stata aperta e conosco il suo contenuto. Sento il cigolio di quel vecchio mobile che le ha lasciato la nonna, sento che ne estrae qualcosa e avverto che la posa sul letto. Poi non avverto pi&ugrave; la sua presenza nella stanza, la chiamo e non risponde, sento lo scroscio dell'acqua nella stanza da bagno. Mi sembrano attimi lunghissimi ma poi la risenti rientrare e poggiare qualcosa sul comodino.</p>
<p>&Egrave; solo un attimo poi avverto le mie parti intime bagnate, mi massaggia il pube con acqua e sapone e comincio a mugolare ma ancora non so cosa mi aspetta. Si ferma per pochi secondi e poi avverto il secco rumore di una lametta che recide i miei folti peli.</p>
<p>&Egrave; inconfondibile quel rumore, la supplico di non farlo, le dico che non mi sono mai depilato, che non voglio ma lei mi ordina di tacere, dice che sono il suo schiavo, che pi&ugrave; oser&ograve; contraddire ai suoi ordini e pi&ugrave; mi infligger&agrave; delle punizioni.</p>
<p>Sono esterrefatto, Eliana non era mai arrivata a tanto.</p>
<p>Quando ha finito l'operazione avverto l'ennesima sensazione di freddo sul mio pube, &egrave; crema profumata, si sente l'odore forte di mela e frutti bosco. Sento le sue mani che spalmano, poi risalgono sul mio uccello e con colpettini decisi lo torturano per poi passare al mio ano, lo allargano, lo aprono. Quell'olio profumato impregna le mie pareti anali, sento le dita di Eliana che vanno avanti e indietro, le sento girare nel mio ventre e arrivare fino alla prostata.</p>
<p>Non ho dimenticato quell'aggeggio che avevo sentito appoggiare sulla sponda del letto e mi domando a cosa servir&agrave; e ne ho timore, autentica paura. Sento Eliana che lo prende, si avvicina al mio buchino e vi infila qualcosa di molto freddo.</p>
<p>Sento il mio sfintere riempirsi prima di un oggetto molto piccolo poi sempre pi&ugrave; grande, fino a sentirmi pieno. Sono esausto, sto malissimo, vorrei prenderla e non so come dirglielo, ho paura di urtare la sua sensibilit&agrave;.</p>
<p>Conosco troppo bene Eliana, deve deciderlo lei, io sono il suo schiavo non valgo nulla. Le mie paure si intensificano quando non avverto pi&ugrave; nessuna presenza nella camera.</p>
<p>Sono l&igrave;, steso su quel letto, incatenato alla sponda, ho lo sfintere pieno di quelle che penso siano palline cinesi e in pi&ugrave; mi ha lasciato implume come un pulcino e bendato.</p>
<p>La mia paura diventa terrore quando sento chiudere la porta di casa con due mandate e poi il nulla, il silenzio completo. Rimango cos&igrave; per un'eternit&agrave;, non so se ridere o piangere, credo che per un po' mi sia addormentato.</p>
<p>Avverto la presenza di Eliana nella camera e il mio cuore ha come un sobbalzo, finalmente la mia padrona &egrave; tornata! La sento spogliarsi, sento le sue cosce salire a cavalcioni su di me, avverto l'odore piacevole della sua fighetta depilata sulla mia bocca. Sono come impazzito, la mia lingua cerca gli anfratti pi&ugrave; oscuri di quel dolce frutto e finalmente mi pare di avvertire un mugolio, i suoi umori mi bagnano il volto.</p>
<p>Non oso chiederle di penetrarla, non oso, so che se chiedo mi sar&agrave; negato.</p>
<p>Poi la sento, sento il suo corpo scendere fino al mio membro eretto, sento le sue labbra assaporarlo, sto per scoppiare ma lei con due dita mi stringe. Mi toglie le manette, mi leva la benda, estrae le palline cinesi dal mio ano lentamente, molto lentamente ed io sento che il mio buco si &egrave; trasformato in una voragine.</p>
<p>Poi lascia che io la penetri ed io non faccio in tempo a prenderla per le natiche che gi&agrave; la mia sborra le invade le viscere. Rotoliamo insieme su quel letto con le lenzuola di seta nera ma lei mi riporta all'ordine, non &egrave; nel suo stile fare troppi complimenti.</p>
<p>Si riveste, mi mette una specie di guinzaglio e poi fa camminare a gattoni fino alla sua poltrona preferita poi si accomoda ed io rimango l&igrave; in silenzio, accucciato come un fedele cagnolino mentre lei mi accarezza il capo di tanto in tanto, solo quel poco che basta per farmi capire che in fondo sono stato uno schiavo perfetto.</p>